// src/utils/getRandomVerse.js

export function getRandomVerse(requestedCategory) {
  const fortunes = {
    "재물운": [ 
      { ko: "마른 나무가 봄을 만나 마침내 꽃이 피고 재물이 집에 가득하도다.", en: "A dry tree meets spring, flowers finally bloom, and wealth fills the house." },
      { ko: "천금의 보배가 문 앞에 이르니 집안에 웃음꽃이 활짝 피어나리라.", en: "A treasure of great value arrives at the door, and flowers of laughter bloom." },
      { ko: "남쪽에서 귀한 보배가 들어오니 뜻밖의 횡재로 가산이 풍성해진다.", en: "Noble treasures come from the south, enriching the household with unexpected fortune." },
      { ko: "길을 가다 금을 얻는 격이니 그 기쁨이 끝이 없고 만인이 부러워하리라.", en: "It is like finding gold on the road; the joy is endless and everyone envies it." },
      { ko: "재성이 문을 비추니 구하지 않아도 재물이 스스로 찾아오는 형국이라.", en: "The star of wealth shines on the door, so fortune finds its way to you on its own." },
      { ko: "동쪽에서 상서로운 기운이 불어오니 쌓인 재물이 산과 같도다.", en: "A propitious energy blows from the east, and wealth piles up like a mountain." },
      { ko: "금과 옥이 방안에 가득 차니 가문의 이름이 사방에 떨쳐지리라.", en: "Gold and jade fill the room, and the family name spreads in all directions." },
      { ko: "흐르는 물이 바다를 만나듯 재물이 끊임없이 집안으로 흘러든다.", en: "Like flowing water meeting the sea, wealth flows into the house endlessly." },
      { ko: "정원이 풍요로우니 곡식이 창고에 넘치고 근심이 사라지도다.", en: "The garden is rich, grains overflow in the storehouse, and worries vanish." },
      { ko: "서쪽 하늘에 무지개가 뜨니 재물과 보화가 스스로 굴러들어온다.", en: "A rainbow rises in the western sky, and wealth and treasures roll in on their own." },
      { ko: "황금 같은 기회가 눈앞에 있으니 주저하지 말고 잡아라. 큰 이익이 따르리라.", en: "A golden opportunity is before you; do not hesitate to seize it. Great profit will follow." },
      { ko: "작은 물줄기가 모여 큰 강을 이루듯, 소소한 이익이 모여 큰 재산이 된다.", en: "As small streams gather to form a great river, small profits gather to become great wealth." },
      { ko: "북쪽에서 귀인이 재물을 가지고 오니 집안의 가업이 번창하고 영화를 누린다.", en: "A noble person brings wealth from the north, and the family business flourishes." },
      { ko: "성실히 일한 대가가 배로 돌아오니 통장의 숫자가 기쁘게 늘어가는구나.", en: "The rewards for hard work return twofold, and the numbers in your account increase joyfully." },
      { ko: "땅을 파서 금을 얻는 형국이라, 노력하는 곳마다 결실이 풍성할 것이다.", en: "It is like digging the earth and finding gold; fruits will be abundant wherever you effort." },
      { ko: "재물운이 문턱을 넘었으니 나갔던 돈도 다시 돌아오고 곳간이 가득 찬다.", en: "Wealth has crossed the threshold; spent money returns, and the storehouse fills up." },
      { ko: "생각지 못한 곳에서 배당이나 보너스가 들어오니 마음이 넉넉해지는 하루다.", en: "Unexpected dividends or bonuses arrive from nowhere, making your heart generous." },
      { ko: "막혔던 자금줄이 시원하게 뚫리니 사업 구상이 현실로 이루어지기 시작한다.", en: "The blocked cash flow opens up smoothly, and your business plans start to become reality." },
      { ko: "투자의 안목이 빛을 발하는 시기이니 판단을 믿고 나아가면 큰 결실이 있다.", en: "It is a time when your investment insight shines; trust your judgment and proceed." },
      { ko: "집안에 경사가 있고 재물이 스스로 들어오니 만사가 태평하고 즐겁도다.", en: "There is a celebration in the house, and wealth enters on its own; all is peaceful." },
      { ko: "재물이 샘물처럼 솟아나니 써도 써도 줄지 않는 풍요를 누리리라.", en: "Wealth springs up like a fountain, so you enjoy abundance that never runs dry." },
      { ko: "황금빛 벌판에 서 있는 격이니 거두어들일 수익이 산더미 같도다.", en: "It is like standing in a golden field; the profits to harvest are like a mountain." },
      { ko: "동쪽에서 불어오는 바람에 실려 재운이 집안으로 굴러들어온다.", en: "Carried by the wind from the east, wealth rolls into the house." },
      { ko: "작은 투자로 큰 결실을 보게 되니 안목이 탁월하다는 칭송을 듣는다.", en: "Seeing great results from a small investment, you receive praise for your excellent insight." },
      { ko: "잃었던 재물이 의외의 장소에서 돌아오니 기쁨이 두 배가 되겠구나.", en: "Lost wealth returns from an unexpected place, so your joy will be doubled." },
      { ko: "성실함이 재물 신을 감동시키니 곳간의 열쇠가 늘어가는 형국이라.", en: "Sincerity moves the god of wealth, and the number of keys to your storehouse increases." },
      { ko: "금전운이 머리 위에 머무니 만지는 것마다 돈이 되는 하루로다.", en: "Money luck stays above your head, making everything you touch turn into money today." },
      { ko: "막혔던 자금 흐름이 폭포수처럼 시원하게 뚫리니 근심이 사라진다.", en: "The blocked cash flow opens up like a waterfall, and your worries vanish." },
      { ko: "남의 도움 없이도 스스로 부를 일구니 명성과 재물을 동시에 얻으리라.", en: "Building wealth on your own without help, you gain both fame and fortune." },
      { ko: "하늘이 내린 큰 복으로 가산이 풍성해지고 자손까지 영화를 누린다.", en: "With a great blessing from heaven, the household prospers and descendants enjoy glory." },
      { ko: "재물의 문이 활짝 열렸으니 평소 갖고 싶던 것을 손에 넣게 되리라.", en: "The gate of wealth is wide open, so you will obtain what you have always wanted." },
      { ko: "북방의 수기운이 재물을 도와 가업이 번창하고 수익이 안정된다.", en: "The water energy of the north helps wealth, flourishing the family business and stabilizing income." },
      { ko: "생각지 못한 상속이나 증여의 운이 있으니 문서 관리에 만전을 기하라.", en: "There is luck in unexpected inheritance or gifts, so be thorough in managing documents." },
      { ko: "지갑 속에 돈이 마르지 않으니 주변 사람들에게 베풀어도 넉넉하도다.", en: "Money does not dry up in your wallet, so it is enough even if you give to those around you." },
      { ko: "구름을 뚫고 나온 햇살처럼 재물운이 눈부시게 빛나는 시기이다.", en: "Like sunlight breaking through clouds, your wealth luck is shining brilliantly." },
      { ko: "장사하는 자는 손님이 구름처럼 몰려오니 돈 세는 소리가 끊이지 않는다.", en: "For merchants, customers flock like clouds, and the sound of counting money never ends." },
      { ko: "먼 곳에서 온 귀인이 재물의 길을 안내하니 믿고 따라가면 대길하다.", en: "A noble person from afar guides the way to wealth; following them will be very auspicious." },
      { ko: "투자의 씨앗이 마침내 열매를 맺으니 수확의 기쁨이 온 집안에 가득하다.", en: "The seeds of investment finally bear fruit, and the joy of harvest fills the house." },
      { ko: "욕심을 버리고 정직하게 행하니 재물이 스스로 주인을 알아보고 찾아온다.", en: "Acting honestly without greed, wealth recognizes its owner and finds its way to you." },
      { ko: "금과 옥이 가득한 상자를 얻는 격이니 명예와 부귀를 한 몸에 받으리라.", en: "It is like obtaining a box full of gold and jade; you receive both honor and riches." },
      { ko: "평소 쌓아온 덕이 재물로 변하여 돌아오니 하늘이 돕고 땅이 응하는구나.", en: "The virtue you've built turns into wealth; heaven helps and the earth responds." },
      { ko: "어두운 밤에 길을 찾듯 재물의 맥을 짚으니 큰 부자가 될 징조로다.", en: "Finding the vein of wealth like finding a path in the dark; it's a sign of becoming very rich." },
      { ko: "작은 물고기가 용이 되어 승천하듯 보잘것없던 투자가 큰 거상이 된다.", en: "As a small fish becomes a dragon, a small investment grows into a great fortune." },
      { ko: "서쪽에서 상서로운 기운이 서리니 뜻밖의 상금이나 포상운이 따른다.", en: "A propitious energy settles in the west, bringing unexpected prizes or rewards." },
      { ko: "땅속에 묻혔던 보석이 빛을 발하니 잊고 있던 자산의 가치가 급상승한다.", en: "A buried gem shines; the value of forgotten assets rises sharply." },
      { ko: "막혔던 운로가 열리며 금전의 흐름이 막힘없이 사방으로 소통된다.", en: "The blocked path of luck opens, and the flow of money circulates freely in all directions." },
      { ko: "재물운이 문 앞에 와 있으니 정성을 다해 맞이하면 가산이 넉넉해지리라.", en: "Wealth luck is at the door; welcome it with sincerity and your household will be rich." },
      { ko: "손을 대는 일마다 이득이 남으니 상업에 종사하는 자는 대길할 운이다.", en: "Every task you touch yields profit; for those in commerce, the luck is very auspicious." },
      { ko: "귀인의 도움으로 문서 계약이 성사되니 큰 재물이 들어올 기반이 마련된다.", en: "A contract is finalized with a noble's help, laying the foundation for great wealth." },
      { ko: "창고에 곡식이 넘쳐나니 이웃과 나누어도 부족함이 없는 풍요로운 시기이다.", en: "The storehouse overflows with grain; it's a rich time with enough to share with neighbors." },
      { ko: "작은 물줄기가 모여 큰 강을 이루듯, 소소한 저축이 태산 같은 자산이 되리라.", en: "As small streams gather to form a big river, minor savings will become a mountain of assets." },
      { ko: "동쪽에서 온 귀인이 재물의 문을 열어주니, 생각지 못한 투자 이익이 발생한다.", en: "A noble person from the east opens the door to wealth, bringing unexpected investment profits." },
      { ko: "막혔던 자금줄이 시원하게 뚫리니, 사업이 번창하고 수입이 기하급수적으로 늘어난다.", en: "The blocked financial flow opens up refreshingly, prospering the business and increasing income exponentially." },
      { ko: "나의 신용이 곧 재산이니, 정직한 거래 속에 큰 부의 기틀이 마련되는구나.", en: "Your credit is your property; the foundation of great wealth is laid in honest transactions." },
      { ko: "뜻밖의 횡재수가 있으니, 길을 가다 보석을 얻는 것과 같은 행운이 따른다.", en: "There is an unexpected windfall, like the luck of finding a gem while walking on the road." },
      { ko: "오래전에 묻어두었던 문서가 빛을 발하니, 부동산이나 주식에서 큰 이득을 본다.", en: "Document filed away long ago shines, bringing great profit from real estate or stocks." },
      { ko: "재물의 신이 나를 보고 웃으니, 만지는 것마다 황금으로 변하는 마법 같은 시기이다.", en: "The god of wealth smiles at you; it is a magical time when everything you touch turns to gold." },
      { ko: "나의 지혜가 돈을 부르니, 날카로운 분석력으로 큰 자산의 흐름을 거머쥔다.", en: "Your wisdom attracts money; you grasp the flow of great assets with sharp analytical skills." },
      { ko: "지출을 줄이고 내실을 다지니, 곳간이 가득 차고 마음마저 넉넉해지는구나.", en: "Reducing spending and strengthening internal stability, the storehouse fills and even the mind grows generous." },
      { ko: "가족과 함께하는 사업에 큰 복이 깃드니, 가문의 재산이 대대로 이어질 징조로다.", en: "Great blessings dwell in the family business; a sign that family wealth will continue for generations." },
      { ko: "나의 명성이 높아짐에 따라 재물도 자연히 따르니, 이름값이 곧 돈이 되는 시기이다.", en: "As your reputation rises, wealth naturally follows; it's a time when your name value becomes money." },
      { ko: "서쪽으로 움직이면 큰 금전적 이득이 기다리고 있으니, 기회를 놓치지 마라.", en: "If you move toward the west, great financial gain awaits; do not miss the opportunity." },
      { ko: "작은 씨앗이 거목이 되듯, 오늘 시작하는 작은 투자가 훗날 커다란 연금이 된다.", en: "As a small seed becomes a giant tree, a small investment started today becomes a huge pension later." },
      { ko: "나의 성실함이 하늘을 감동시켜, 노력 이상의 막대한 보상이 통장에 기록된다.", en: "Your sincerity moves heaven, and a massive reward beyond effort is recorded in your bank account." },
      { ko: "새로운 사업 파트너가 재물의 열쇠를 쥐고 나타나니, 협력하여 부를 일구어라.", en: "A new business partner appears holding the key to wealth; build fortune through cooperation." },
      { ko: "돈의 흐름을 읽는 안목이 생기니, 세상의 부가 나의 손안으로 쏟아지는도다.", en: "Gaining an eye for the flow of money, the world's wealth pours into your hands." },
      { ko: "불필요한 욕심을 버리면 더 큰 재물이 찾아오니, 비움으로써 채우는 법을 배우라.", en: "If you let go of unnecessary greed, greater wealth comes; learn to fill by emptying." },
      { ko: "오늘은 계약이나 서명에 매우 유리한 날이니, 큰 문서가 오가는 기쁨이 있다.", en: "Today is a very favorable day for contracts or signatures; there is joy in exchanging large documents." },
      { ko: "나의 취미가 수익으로 연결되니, 즐기면서 돈을 버는 이상적인 상황이 펼쳐진다.", en: "Your hobby leads to profit, unfolding an ideal situation where you earn money while enjoying." },
      { ko: "흩어졌던 재물이 다시 모이니, 잃어버렸던 원금을 회복하고 수익까지 챙긴다.", en: "Scattered wealth gathers again; you recover the lost principal and even take profits." },
      { ko: "나의 직감이 재물운과 맞물리니, 망설임 없는 선택이 커다란 부의 지름길이 된다.", en: "Your intuition meshes with wealth luck; a choice without hesitation becomes a shortcut to great fortune." },
      { ko: "땅의 기운이 나를 도우니, 토지나 건물 등 부동 자산의 가치가 급상승한다.", en: "The energy of the earth helps you; the value of fixed assets like land or buildings skyrockets." },
      { ko: "주변의 시기 질투를 막아내고 지킨 재물이니, 더욱 단단하고 견고한 성이 되리라.", en: "Wealth protected against the envy of others will become an even firmer and more solid castle." },
      { ko: "나의 절약 정신이 빛을 발하여, 불필요한 누수가 막히고 자산이 급격히 불어난다.", en: "Your frugality shines; unnecessary leaks are stopped and assets grow rapidly." },
      { ko: "뜻밖의 상속이나 증여의 운이 있으니, 가문의 내력이 나의 부를 지탱해 준다.", en: "Luck with an unexpected inheritance or gift; family history supports your wealth." },
      { ko: "오늘은 금전적 이득을 위해 행동하기 최적의 날이니, 주저 말고 시장으로 나가라.", en: "Today is the optimal day to act for financial gain; do not hesitate and go out to the market." },
      { ko: "나의 아이디어가 특허와 권리가 되어, 평생 마르지 않는 샘물 같은 재물이 된다.", en: "Your idea becomes a patent and a right, turning into wealth like a never-drying spring." },
      { ko: "어려운 시절을 견뎌낸 보람이 있어, 이제부터는 탄탄대로의 금전운이 펼쳐진다.", en: "It was worth enduring difficult times; from now on, a solid path of financial luck unfolds." },
      { ko: "나의 신용도가 최고조에 달하니, 낮은 금리로 큰 자금을 운용할 기회를 얻는다.", en: "Your credit rating reaches its peak, gaining an opportunity to manage large funds at low interest." },
      { ko: "주변 사람들에게 베푼 호의가 재물이 되어 돌아오니, 덕을 쌓는 것이 곧 부의 비결이다.", en: "Favors to others return as wealth; building virtue is the secret to wealth." },
      { ko: "나의 자산 포트폴리오가 완벽한 조화를 이루니, 위험은 줄고 수익은 극대화된다.", en: "Your asset portfolio is in perfect harmony; risk decreases and profit is maximized." },
      { ko: "오늘은 재물의 기운이 북쪽에서 강하게 들어오니, 북쪽으로 고개를 돌려라.", en: "Today, the energy of wealth flows strongly from the north; turn your head to the north." },
      { ko: "나의 냉철한 판단이 손실을 막고, 오히려 그것을 기회로 삼아 큰돈을 번다.", en: "Your cold judgment prevents losses and instead uses them as an opportunity to make big money." },
      { ko: "작은 장사로 시작하여 거대한 기업을 일구는 형국이니, 시작은 미약하나 끝은 창대하리라.", en: "Starting as a small business to build a giant enterprise; the start is weak but the end will be grand." },
      { ko: "나의 저축 습관이 행운과 만나, 예상치 못한 복리 이자의 혜택을 톡톡히 누린다.", en: "Your saving habits meet luck, enjoying the benefits of unexpected compound interest." },
      { ko: "오늘은 물건을 사거나 팔기에 매우 좋은 날이니, 거래에서 큰 이윤을 남긴다.", en: "Today is a very good day to buy or sell items, leaving a large profit in transactions." },
      { ko: "나의 성실함이 직장에서 승진과 보너스로 이어지니, 근로 소득이 대폭 상승한다.", en: "Your diligence leads to promotion and bonuses at work, significantly increasing labor income." },
      { ko: "어두운 터널을 지나 빛을 보듯, 부채의 늪에서 벗어나 순자산이 늘어나는구나.", en: "Like seeing light through a dark tunnel, you escape the swamp of debt and net assets increase." },
      { ko: "나의 인맥이 곧 정보이고 재물이니, 좋은 사람들과의 교류가 부의 원천이 된다.", en: "Your network is information and wealth; exchange with good people is the source of wealth." },
      { ko: "오늘은 뜻밖의 경품이나 이벤트 당첨운이 있으니, 소소한 행운을 놓치지 마라.", en: "Today, there is luck in unexpected prizes or event winnings; do not miss small fortunes." },
      { ko: "나의 창의적인 투자가 시장의 판도를 바꾸니, 선구자로서 막대한 부를 선점한다.", en: "Your creative investment changes the market's landscape, preoccupying massive wealth as a pioneer." },
      { ko: "안정적인 자산 운용이 최고의 전략이니, 무리한 투기보다 안전한 자산을 선호하라.", en: "Stable asset management is the best strategy; prefer safe assets over excessive speculation." },
      { ko: "나의 이름으로 된 문서가 늘어나니, 재산 목록이 하루가 다르게 길어지는도다.", en: "Documents in your name increase; the list of properties grows longer day by day." },
      { ko: "오늘은 재물을 지키기에 좋은 날이니, 불필요한 지출을 막고 내실을 기하라.", en: "Today is a good day to protect wealth; stop unnecessary spending and focus on internal stability." },
      { ko: "나의 배움이 재물로 치환되니, 자격증이나 새로운 기술이 부의 열쇠가 된다.", en: "Your learning is substituted for wealth; certificates or new skills become the key to wealth." },
      { ko: "하늘에서 돈벼락이 내리는 꿈을 꾸었다면, 현실에서도 그에 상응하는 복이 찾아온다.", en: "If you dreamed of money falling from the sky, a corresponding blessing will find you in reality." },
      { ko: "나의 신념이 재물운을 강화하니, 확신을 가지고 추진하는 사업에서 큰 성과가 난다.", en: "Your belief strengthens wealth luck; great results come from businesses pushed with conviction." },
      { ko: "오늘은 귀한 선물을 받거나 대접을 받는 운이니, 재물 이상의 기쁨이 가득하다.", en: "Today, you're destined to receive a precious gift or hospitality; it's full of joy beyond wealth." },
      { ko: "나의 꾸준함이 복권 당첨보다 나은 결과를 가져오니, 성실이 최고의 재테크로다.", en: "Your consistency brings better results than winning the lottery; sincerity is the best financial tech." },
      { ko: "재물의 흐름이 나를 향해 굽이쳐 들어오니, 평생 쓸 부의 원천을 마련하는 시기이다.", en: "The flow of wealth curves toward you; it is a time to prepare the source of lifelong wealth." },
      { ko: "나의 신용이 황금보다 귀하게 쓰이니, 큰 자금을 움직이는 거상의 운세로다.", en: "Your credit is used more preciously than gold; it's the fortune of a great merchant moving large funds." },
      { ko: "뿌린 대로 거두는 법, 그간의 성실한 저축이 복리의 마법을 부려 큰 자산이 된다.", en: "As you reap what you sow, your sincere savings perform the magic of compound interest to become a great asset." },
      { ko: "오늘은 문서를 잡기에 최적인 날이니, 부동산이나 계약에서 예상 밖의 큰 이득이 있다.", en: "Today is the optimal day to handle documents; there is an unexpected large profit in real estate or contracts." },
      { ko: "나의 아이디어가 시장의 흐름을 바꾸니, 가만히 있어도 저작권료와 인센티브가 쏟아진다.", en: "Your ideas change the market flow; royalties and incentives pour in even if you stay still." },
      { ko: "서쪽에서 반가운 소식이 들려오니, 과거에 빌려준 돈이나 잊고 있던 배당금을 받게 되리라.", en: "Good news comes from the west; you will receive money lent in the past or forgotten dividends." },
      { ko: "나의 안목이 진흙 속의 진주를 찾아내니, 저평가된 자산이 폭발적으로 상승하는 기쁨이 있다.", en: "Your insight finds a pearl in the mud; there is joy in the explosive rise of undervalued assets." },
      { ko: "재물은 흐르는 물과 같으나, 오늘은 그 물길이 나의 집 마당으로 굽이쳐 들어오는구나.", en: "Wealth is like flowing water, but today that watercourse curves into your house's yard." },
      { ko: "나의 인맥이 곧 금맥이니, 귀인과의 식사 자리에서 일생일대의 투자 정보를 얻게 된다.", en: "Your network is your gold vein; you obtain a once-in-a-lifetime investment info at a dinner with a noble person." },
      { ko: "지출은 줄고 수입은 늘어나니, 통장의 잔고가 앞자리를 바꾸며 나를 미소 짓게 한다.", en: "Spending decreases and income increases; the bank balance changes its first digit and makes you smile." },
      { ko: "나의 성실함이 하늘을 감동시켜, 노력의 대가 이상의 막대한 성과급을 거머쥐게 되도다.", en: "Your sincerity moves heaven, and you grasp a massive performance bonus beyond the price of effort." },
      { ko: "오늘은 금전적 승부수가 통하는 날이니, 확신이 있다면 과감하게 투자 비중을 늘려라.", en: "Today is a day when financial gambles work; if you have conviction, boldly increase your investment weight." },
      { ko: "나의 가업이 번창하여 대대손손 물려줄 탄탄한 부의 기틀이 완성되는 시기이다.", en: "Your family business prospers; it's a time when the solid foundation of wealth to be handed down is completed." },
      { ko: "횡재수가 강력하니 길가다 얻는 작은 이득부터 복권에 이르기까지 운의 기운이 충만하다.", en: "The windfall luck is strong; from small gains on the street to lotteries, the energy of luck is full." },
      { ko: "나의 냉철한 판단이 손실을 막아주니, 위기 속에서 오히려 자산의 가치를 지켜내리라.", en: "Your cold judgment prevents losses; you will protect the value of assets even in a crisis." },
      { ko: "오늘은 재물의 기운이 남쪽에서 강하게 들어오니, 계약이나 협상은 남쪽에서 진행하라.", en: "The energy of wealth flows strongly from the south today; proceed with contracts or negotiations in the south." },
      { ko: "나의 명성이 높아질수록 부의 크기도 비례하니, 이름값이 곧 천금의 가치를 지닌다.", en: "As your reputation rises, the size of wealth increases proportionally; your name value is worth a thousand gold." },
      { ko: "막혔던 자금의 혈맥이 뚫리니 사업 자금이 넉넉해지고 모든 결제가 순조롭게 풀린다.", en: "The blocked vein of funds opens; business capital becomes sufficient and all payments are unraveled smoothly." },
      { ko: "나의 검소함이 복을 부르는 그릇이 되어, 낭비 없는 삶 속에 큰 재물이 차곡차곡 쌓인다.", en: "Your frugality becomes a vessel for fortune; great wealth accumulates steadily in a waste-free life." },
      { ko: "오늘은 뜻밖의 경품이나 이벤트에서 1등의 영예를 안게 되는 즐거운 운세이다.", en: "Today is a joyful fortune where you take the honor of first place in unexpected prizes or events." },
      { ko: "나의 지혜로운 분산 투자가 빛을 발하니, 시장의 변동성에도 내 자산은 굳건히 성장한다.", en: "Your wise diversified investment shines; your assets grow firmly despite market volatility." },
      { ko: "나의 기술력이 독점적인 가치를 인정받아, 부르는 게 값인 거액의 계약을 체결하게 되도다.", en: "Your technology is recognized for its monopoly value, leading to a huge contract at your asking price." },
      { ko: "오늘은 빌려준 돈을 돌려받거나 보상금을 받는 등 현금 흐름이 매우 원활한 날이다.", en: "Today is a day of very smooth cash flow, such as getting back lent money or receiving compensation." },
      { ko: "나의 직감이 보물 탐지기가 되니, 내가 선택한 종목이 시장의 대장주가 되는 기쁨이 있다.", en: "Your intuition becomes a treasure detector; there's joy in your chosen item becoming a market leader." },
      { ko: "작은 이익에 연연하지 않고 큰 판을 읽으니, 결국 거대한 부의 흐름을 주도하게 된다.", en: "Without clinging to small profits, you read the big picture and eventually lead the flow of great wealth." },
      { ko: "나의 성품이 온화하니 주변에서 서로 돈이 되는 정보를 가져다주는 형국이다.", en: "Your character is gentle, so it's a situation where people around you bring profitable information." },
      { ko: "오늘은 쇼핑을 해도 이득인 날이니, 필요한 물건을 아주 저렴한 가격에 득템하게 된다.", en: "Today is a day when even shopping is a gain; you get necessary items at a very low price." },
      { ko: "나의 꾸준한 노력이 연금 같은 수익으로 돌아오니, 노후 걱정 없는 탄탄한 부를 쌓는다.", en: "Your steady efforts return as pension-like income, building solid wealth without worries for old age." },
      { ko: "하늘에서 재물이 비처럼 내리는 형상이니, 내가 벌린 그릇의 크기만큼 부를 담게 되리라.", en: "It's a shape of wealth falling like rain from the sky; you will hold wealth as much as the size of the vessel you open." },
      { ko: "나의 신규 사업 아이템이 투자자들의 마음을 사로잡아, 막대한 자금 유치에 성공한다.", en: "Your new business item captures investors' hearts, succeeding in attracting massive funds." },
      { ko: "오늘은 금전적으로 매우 길한 날이니, 지갑 속에 행운의 지폐가 가득 차는 기쁨이 있다.", en: "Today is a very auspicious day financially; there's joy in your wallet being full of lucky bills." },
      { ko: "나의 상상력이 현실의 화폐가 되니, 창작 활동이 곧 막대한 부의 창출로 이어진다.", en: "Your imagination becomes real currency; creative activities lead directly to the creation of massive wealth." },
      { ko: "어려운 시기에 사둔 자산이 효자 노릇을 하니, 인내의 대가가 수십 배의 수익으로 돌아온다.", en: "Assets bought during hard times act like a dutiful son; the price of patience returns as dozens of times profit." },
      { ko: "나의 정직함이 거래처의 신뢰를 얻어, 장기적이고 안정적인 고수익 구조를 확보한다.", en: "Your honesty wins the trust of clients, securing a long-term, stable high-profit structure." },
      { ko: "오늘은 돈을 쓰는 것보다 지키는 것이 이득이니, 충동구매를 삼가면 큰 돈을 번 것과 같다.", en: "Today, saving is better than spending; if you refrain from impulse buying, it's like making big money." },
      { ko: "나의 이름이 브랜드가 되어 가치가 상승하니, 앉아만 있어도 재물이 나를 찾아온다.", en: "Your name becomes a brand and its value rises; wealth finds you even while you are sitting." },
      { ko: "지인의 추천으로 시작한 투자가 대박의 시발점이 되니, 오늘은 주변의 말에 귀를 기울여라.", en: "An investment started by a friend's recommendation becomes the starting point of a jackpot; listen to others today." },
      { ko: "나의 열정이 재물을 태우는 불꽃이 아니라 부를 키우는 엔진이 되어 거침없이 나아간다.", en: "Your passion is not a flame that burns wealth, but an engine that grows wealth, moving forward without hesitation." },
      { ko: "오늘은 복권을 사거나 경품 응모를 하기에 최적의 기운이니, 자신의 운을 시험해 보라.", en: "Today is the optimal energy to buy a lottery ticket or enter a prize draw; test your luck." },
      { ko: "나의 분석대로 시장이 움직이니, 전문가들도 부러워할 만한 높은 수익률을 기록한다.", en: "The market moves as you analyzed, recording a high return rate that even experts would envy." },
      { ko: "재물운이 절정에 달했으니, 이제는 부를 관리하고 나누는 지혜를 발휘할 시기이다.", en: "Wealth luck has reached its peak; now is the time to exercise wisdom in managing and sharing wealth." },
      { ko: "나의 절약 습관이 행운의 파도와 만나, 생각보다 훨씬 빠르게 목돈 마련의 꿈을 이룬다.", en: "Your saving habits meet the wave of luck, achieving the dream of saving a large sum much faster than expected." },
      { ko: "오늘은 동북쪽 방향에서 금전적인 행운이 오니, 중요한 미팅은 그쪽에서 하라.", en: "Financial luck comes from the northeast today; hold important meetings in that direction." },
      { ko: "나의 고유한 재능이 상업적 성공으로 변환되니, 세상에 하나뿐인 부의 통로를 개척한다.", en: "Your unique talent is converted into commercial success, pioneering a one-of-a-kind wealth channel." },
      { ko: "막연했던 부자의 꿈이 구체적인 숫자로 실현되니, 자산 증식의 재미가 쏠쏠한 날이다.", en: "The vague dream of being rich is realized in concrete numbers; it's a day of great fun in asset growth." },
      { ko: "나의 인덕이 재물로 돌아오니, 과거에 베풀었던 호의가 오늘 커다란 보상으로 찾아온다.", en: "Your virtue returns as wealth; the favors you gave in the past find you today as a great reward." },
      { ko: "오늘은 계약서의 도장을 찍기 전 마지막으로 검토하라. 작은 수정이 큰 손실을 막아준다.", en: "Review one last time before stamping the contract today. A small correction prevents a large loss." },
      { ko: "나의 자산이 스스로 일하는 구조가 완성되니, 진정한 경제적 자유에 한 걸음 더 다가선다.", en: "The structure where your assets work for themselves is completed, moving one step closer to true financial freedom." },
      { ko: "어려운 이웃을 돕는 선행이 재물운을 더욱 강하게 하니, 베풀수록 곳간이 더 빨리 차오른다.", en: "Good deeds to help neighbors strengthen wealth luck; the more you give, the faster the storehouse fills." },
      { ko: "나의 신념이 재물의 기운을 안정시키니, 풍파 속에서도 나의 자산은 결코 흔들리지 않는다.", en: "Your belief stabilizes the energy of wealth; your assets will never shake even in storms." },
      { ko: "재물의 흐름이 황금빛 용처럼 나를 감싸 안으니, 일생을 통틀어 가장 강력한 부의 기운이로다.", en: "The flow of wealth embraces you like a golden dragon; it's the strongest energy of wealth in your entire life." }/* 데이터 삽입 예정 */ ],
    "대인운": [
      { ko: "길에서 귀인을 만나니 막혔던 일이 풀리고 앞길이 훤히 열리도다.", en: "Meeting a noble person on the road, blocked paths clear and the future opens wide." },
      { ko: "어진 벗이 찾아와 도움을 주니 천군만마를 얻은 듯 든든하구나.", en: "A virtuous friend visits to help; it feels as reassuring as gaining a vast army." },
      { ko: "사방에서 사람들이 나를 도우니 명성이 높아지고 인덕이 넘쳐난다.", en: "People from all directions help me; my fame rises and my virtue overflows." },
      { ko: "윗사람의 끌어줌을 입으니 평소 바라던 소망이 쉽게 이루어지리라.", en: "With the guidance of a superior, long-held wishes will be easily fulfilled." },
      { ko: "용이 구름을 얻은 격이니 출중한 인물들이 내 곁으로 모여든다.", en: "Like a dragon gaining clouds, outstanding individuals gather by my side." },
      { ko: "다투던 이와 화해하니 악연이 선연으로 바뀌어 복이 되어 돌아온다.", en: "Reconciling with an opponent, a bad relationship turns into a good one and brings blessing." },
      { ko: "말 한마디로 천 냥 빚을 갚으니 주변의 칭송이 자자하도다.", en: "Repaying a great debt with a single word, praise from those around is abundant." },
      { ko: "먼 곳에서 반가운 소식이 오고 귀한 손님이 집안을 방문하리라.", en: "Good news comes from afar, and a noble guest will visit the home." },
      { ko: "여러 사람의 마음이 하나로 합쳐지니 큰일을 도모하기에 부족함이 없다.", en: "As many hearts become one, there is no lack in planning great things." },
      { ko: "덕을 쌓으니 만인이 우러러보고 따르는 자가 줄을 잇는구나.", en: "Building virtue, ten thousand people look up to you, and followers line up." },
      { ko: "구름이 걷히고 달이 나타나듯, 오해가 풀리고 진심이 통하는 시기이다.", en: "As clouds clear and the moon appears, misunderstandings dissolve and sincerity reaches others." },
      { ko: "동료와의 협력이 빛을 발하니 혼자보다 둘이서 더 큰 성과를 낸다.", en: "Collaboration with colleagues shines; two achieve more than one." },
      { ko: "겸손한 태도가 귀인을 부르니 스스로를 낮출수록 운이 상승한다.", en: "A humble attitude invites noble people; the more you lower yourself, the higher your luck rises." },
      { ko: "오래된 인연이 새로운 기회를 가져다주니 옛 친구에게 연락해 보라.", en: "Old connections bring new opportunities; try reaching out to an old friend." },
      { ko: "나를 시기하던 자가 물러가고 진정한 조력자가 나타나 힘을 보탠다.", en: "Jealous detractors step back, and true supporters appear to lend their strength." },
      { ko: "말씨가 고우니 듣는 이가 즐겁고, 그 즐거움이 나에게 복이 되어 돌아온다.", en: "Kind words please the listener, and that pleasure returns to you as a blessing." },
      { ko: "낯선 곳에서 뜻밖의 인연을 맺으니 그가 장차 나의 큰 스승이 되리라.", en: "Making an unexpected connection in a strange place, they will later become a great mentor." },
      { ko: "주변의 칭송이 자자하니 명예가 올라가고 따르는 무리가 늘어나는구나.", en: "Praise from those around you rises, honor increases, and followers grow in number." },
      { ko: "화목한 가정이 만사의 근본이니 집안 사람들과 먼저 소통하라.", en: "A harmonious family is the root of all things; communicate with your family members first." },
      { ko: "진심 어린 충고를 해주는 이를 만나니 인생의 갈림길에서 올바른 선택을 한다.", en: "Meeting someone who gives sincere advice, you make the right choice at life's crossroads." },
      { ko: "남의 허물을 덮어주고 장점을 치켜세우니 만인이 나를 우러러보도다.", en: "Covering others' flaws and praising their strengths, everyone looks up to you." },
      { ko: "함께 고난을 겪은 이와 기쁨을 나누니 우정이 강철처럼 단단해지는구나.", en: "Sharing joy with those who endured hardships together, friendship becomes as strong as steel." },
      { ko: "오해가 눈 녹듯 사라지고 서먹했던 관계가 봄날처럼 따스하게 풀린다.", en: "Misunderstandings melt away like snow, and awkward relationships thaw like a spring day." },
      { ko: "나를 진심으로 아끼는 스승을 만나니 앞날의 안개가 걷히고 길이 보인다.", en: "Meeting a mentor who truly cares, the fog of the future lifts and the path appears." },
      { ko: "작은 배려가 큰 감동이 되어 돌아오니 주변에 적이 없고 아군만 가득하다.", en: "Small acts of kindness return as great touched emotions; there are no enemies, only allies." },
      { ko: "말보다 행동으로 신뢰를 쌓으니 거래처와 동료들의 신망이 두텁도다.", en: "Building trust through actions rather than words, the confidence of clients and colleagues is deep." },
      { ko: "뜻이 맞는 동료들과 의기투합하니 불가능해 보이던 일도 현실이 된다.", en: "Uniting with like-minded colleagues, even seemingly impossible tasks become reality." },
      { ko: "어려운 처지에 놓인 이를 도우니 훗날 그가 나의 가장 큰 조력자가 되리라.", en: "Helping someone in difficulty, they will become your greatest supporter in the future." },
      { ko: "부드러운 카리스마가 빛을 발하니 자연스럽게 사람들을 이끄는 리더가 된다.", en: "Soft charisma shines, naturally making you a leader who guides people." },
      { ko: "멀리 있던 형제가 찾아와 힘을 보태니 집안의 근심이 사라지고 웃음이 난다.", en: "A long-absent sibling visits to help, so family worries vanish and laughter arises." },
      { ko: "정직한 마음으로 대하니 적조차 감동하여 나의 편으로 돌아서는구나.", en: "Acting with an honest heart, even enemies are moved and turn to your side." },
      { ko: "주변 사람들의 조언을 귀담아들으니 큰 실수를 피하고 기회를 얻는다.", en: "Listening carefully to the advice of those around you, you avoid big mistakes and gain opportunities." },
      { ko: "나의 재능을 알아주는 이를 만나니 물 만난 고기처럼 활약하게 되리라.", en: "Meeting someone who recognizes your talent, you will flourish like a fish in water." },
      { ko: "오랜 시간 공들인 인맥이 결실을 맺어 결정적인 순간에 큰 힘이 된다.", en: "Connections built over a long time bear fruit, becoming a great strength at the decisive moment." },
      { ko: "상대방의 입장을 먼저 생각하니 불필요한 다툼이 사라지고 평화가 온다.", en: "Thinking of the other person's perspective first, unnecessary conflicts disappear and peace arrives." },
      { ko: "먼저 손을 내미는 용기가 있으니 끊어졌던 인연이 다시 이어지리라.", en: "With the courage to reach out first, broken connections will be re-established." },
      { ko: "나의 진심을 몰라주던 이들이 마침내 나의 진면목을 보고 사과해온다.", en: "Those who didn't understand your sincerity finally see your true self and apologize." },
      { ko: "사람들 사이에서 중재 역할을 잘하니 나의 영향력이 자연스레 커지도다.", en: "Playing the role of mediator well, your influence naturally grows." },
      { ko: "작은 약속도 소중히 여기니 신용이 쌓여 더 큰 기회가 찾아오는구나.", en: "Valuing even small promises, your credibility builds and brings greater opportunities." },
      { ko: "나보다 뛰어난 이와 교류하니 나의 안목과 수준이 한 단계 높아진다.", en: "Interacting with those superior to yourself, your insight and level rise to the next stage." },
      { ko: "멀리 있는 친척보다 가까운 이웃이 힘이 되니 주변 사람을 먼저 챙겨라.", en: "A close neighbor is more helpful than a distant relative; take care of those around you first." },
      { ko: "나의 부족함을 채워줄 완벽한 파트너를 만나니 사업과 인생에 활력이 넘친다.", en: "Meeting a perfect partner who fills your deficiencies, both business and life overflow with vitality." },
      { ko: "원망하던 마음을 내려놓으니 비로소 진정한 인연이 들어올 자리가 생기는구나.", en: "As you let go of resentment, room is finally made for a true connection to enter." },
      { ko: "군계일학처럼 대중 속에서 나의 존재감이 빛나니 많은 이가 나를 따른다.", en: "Like a crane among chickens, your presence shines in the crowd and many follow you." },
      { ko: "부모님의 덕이 나에게 미치니 집안 어른들의 말씀에 귀를 기울이면 길이 열린다.", en: "The virtue of parents reaches you; listening to the elders of the house opens the way." },
      { ko: "나의 성공을 진심으로 기뻐해 주는 이가 곁에 있으니 인생의 큰 복이로다.", en: "Having someone by your side who truly rejoices in your success is a great blessing in life." },
      { ko: "공적인 자리에서 만난 인연이 사적으로도 깊어져 평생의 동반자가 된다.", en: "A connection made in a public setting deepens privately, becoming a lifelong companion." },
      { ko: "작은 오해로 소원했던 친구가 먼저 사과의 손길을 내미니 기쁘게 맞이하라.", en: "A friend estranged by a small misunderstanding reaches out first with an apology; welcome them joyfully." },
      { ko: "나의 겸손함이 상대의 마음을 움직이니 어려운 부탁도 흔쾌히 들어주는구나.", en: "Your humility moves the other's heart, making them willingly grant even difficult requests." },
      { ko: "좋은 스승 밑에서 배움을 얻으니 나의 인격과 학식이 날로 깊어지는 시기이다.", en: "Gaining learning under a good mentor, your character and knowledge deepen day by day." },],
    "성취운": [ 
      { ko: "학문이나 기술에 정진하니 마침내 세상이 나의 이름을 기억하기 시작한다.", en: "Devoting yourself to studies or skills, the world finally begins to remember your name." },
      { ko: "준비된 자에게 기회가 오듯, 공들인 탑이 무너지지 않고 결실을 맺는다.", en: "As opportunities come to the prepared, the tower built with effort does not fall and bears fruit." },
      { ko: "어려운 시험이나 자격증 취득에 길운이 따르니 합격의 기쁨이 눈앞에 있다.", en: "Auspicious luck follows difficult exams or certifications; the joy of passing is near." },
      { ko: "직장에서 승진하거나 큰 프로젝트를 맡게 되니 나의 능력을 입증할 때이다.", en: "With a promotion or a major project at work, it's time to prove your capabilities." },
      { ko: "지성이면 감천이라, 간절히 원하던 목표가 하늘의 도움으로 이루어지도다.", en: "Sincerity moves heaven; the goal you earnestly desired is achieved with celestial help." },
      { ko: "가뭄에 단비가 내리듯, 지체되었던 허가나 승인 소식이 시원하게 들려온다.", en: "Like sweet rain in a drought, news of delayed permits or approvals arrives smoothly." },
      { ko: "작은 아이디어가 큰 사업으로 번창하니 나의 창의성이 빛을 발하는 시기이다.", en: "A small idea flourishes into a big business; it's a time when your creativity shines." },
      { ko: "경쟁자들을 물리치고 선두에 서니 나의 지위가 견고해지고 위엄이 선다.", en: "Defeating competitors and taking the lead, your position becomes firm and dignified." },
      { ko: "포기하고 싶던 순간을 견뎌내니 마침내 정상에서 발아래를 굽어보게 되는구나.", en: "Enduring the moment you wanted to give up, you finally look down from the summit." },
      { ko: "나의 작품이나 성과가 널리 알려져 만인의 박수와 갈채를 한 몸에 받으리라.", en: "Your work or achievements become widely known, receiving the applause of all." },
      { ko: "계획했던 일이 순풍에 돛 단 듯 나아가니 예상보다 빠르게 목표에 도달한다.", en: "Planned tasks move like a ship with a tailwind, reaching the goal faster than expected." },
      { ko: "나의 노력이 결실을 맺어 상장이나 훈장을 받으니 가문의 영광이로다.", en: "Your efforts bear fruit, receiving awards or medals; it is the glory of the family." },
      { ko: "막혔던 아이디어가 샘솟듯 터져 나오니 창작 활동에 큰 진전이 있겠구나.", en: "Blocked ideas burst forth like a spring, leading to great progress in creative activities." },
      { ko: "정정당당하게 승부하여 승리를 거머쥐니 주변의 시샘조차 찬사로 변한다.", en: "Winning through fair play, even the envy of those around you turns into praise." },
      { ko: "꿈에 그리던 직장에 들어가거나 원하는 부서로 발령받는 기쁨이 있다.", en: "There is the joy of joining a dream workplace or being assigned to a desired department." },
      { ko: "작은 성공이 발판이 되어 더 큰 무대로 진출하니 기세가 하늘을 찌른다.", en: "Small successes become a stepping stone to a larger stage; your momentum pierces the sky." },
      { ko: "나의 전문성이 널리 인정받아 여기저기서 나를 찾는 부름이 끊이지 않는다.", en: "Your expertise is widely recognized, and calls seeking you do not cease." },
      { ko: "혼란스러운 상황 속에서도 평정심을 유지하니 결국 최후의 승자가 되리라.", en: "Maintaining composure in confusing situations, you will eventually become the final winner." },
      { ko: "어려운 고비를 넘길 때마다 나의 내공이 쌓여 진정한 고수의 반열에 오른다.", en: "Each time you overcome a difficult hurdle, your inner strength builds, reaching the rank of a master." },
      { ko: "뿌린 대로 거두는 법이니 그동안의 성실함이 마침내 값진 성공으로 돌아온다.", en: "You reap what you sow; your past sincerity finally returns as a valuable success." },
      { ko: "지혜로운 판단으로 위기를 기회로 바꾸니 전화복의 계기가 되리라.", en: "Turning a crisis into an opportunity with wise judgment, it becomes a turning point for blessing." },
      { ko: "묵묵히 걷던 길이 마침내 탄탄대로가 되어 나의 앞길을 축복하는구나.", en: "The path walked silently finally becomes a solid highway, blessing the road ahead." },
      { ko: "나의 성실함이 하늘을 감동시키니 예상치 못한 귀인의 도움으로 목표를 달성한다.", en: "Your sincerity moves heaven, achieving goals with unexpected help from a noble person." },
      { ko: "한 분야의 최고가 되기 위한 시련을 이겨내니 명성이 온 사방에 떨친다.", en: "Overcoming trials to become the best in a field, your fame spreads in all directions." },
      { ko: "작은 물방울이 바위를 뚫듯, 끈기 있는 노력이 거대한 성취를 가져온다.", en: "As a small drop of water pierces a rock, persistent effort brings a massive achievement." },
      { ko: "경쟁에서의 승리보다 자기 자신과의 싸움에서 이기니 진정한 대성공이로다.", en: "Winning the battle with yourself rather than in competition is a true, grand success." },
      { ko: "나의 공로가 정당한 평가를 받으니 직위가 오르고 권위가 세워지는 시기이다.", en: "Your merits receive a fair evaluation; it is a time when your rank rises and authority is established." },
      { ko: "새로운 기술을 습득하여 남들보다 앞서가니 시대의 흐름을 주도하게 된다.", en: "Acquiring new skills and staying ahead of others, you lead the trend of the times." },
      { ko: "어두운 터널을 지나 눈부신 햇살을 맞이하듯, 고생 끝에 낙이 찾아온다.", en: "Like greeting brilliant sunlight after a dark tunnel, joy comes after hardship." },
      { ko: "내가 세운 계획이 차질 없이 진행되니 만인이 나의 통솔력을 우러러본다.", en: "The plans you set proceed without a hitch, so everyone looks up to your leadership." },
      { ko: "정체되었던 운로가 활짝 열리니 공들여 준비한 프로젝트가 대성공을 거둔다.", en: "The stagnant path of luck opens wide, leading your carefully prepared project to great success." },
      { ko: "창의적인 발상이 세상을 놀라게 하니 업계에서 독보적인 위치에 오르도다.", en: "Creative ideas surprise the world, placing you in an unrivaled position in the industry." },
      { ko: "나의 성과가 윗사람의 눈에 드니 파격적인 보상과 승진이 뒤따르는구나.", en: "Your achievements catch the eye of superiors, followed by unconventional rewards and promotions." },
      { ko: "혼란 속에서도 핵심을 꿰뚫어 보니 남들이 보지 못한 성공의 열쇠를 거머쥔다.", en: "Seeing through the core even in confusion, you seize the key to success that others missed." },
      { ko: "학문적 성취가 정점에 달하니 논문이나 저술이 널리 인정을 받게 되리라.", en: "Academic achievement reaches its peak, leading to wide recognition of your papers or writings." },
      { ko: "작은 성공에 안주하지 않고 더 큰 목표를 향하니 기운이 멈추지 않고 상승한다.", en: "Not settling for small success but aiming for larger goals, your energy rises without stopping." },
      { ko: "나의 결단력이 조직을 살리니 지도자로서의 자질을 충분히 입증하는 시기이다.", en: "Your decisiveness saves the organization, fully proving your qualities as a leader." },
      { ko: "어려운 환경에서도 배움을 게을리하지 않으니 때가 되어 큰 빛을 발하는구나.", en: "Not neglecting learning even in difficult environments, you shine brightly when the time comes." },
      { ko: "동료들의 지지 속에 큰 책임을 맡으니 나의 능력을 세상에 떨칠 기회가 왔다.", en: "Taking on great responsibility with the support of colleagues, the chance to show your ability has come." },
      { ko: "거센 파도를 헤치고 항구에 도착하듯, 긴 여정 끝에 바라던 성공을 쟁취한다.", en: "Like arriving at a port through rough waves, you win the desired success after a long journey." },
      { ko: "정직함이 최고의 전략이니 편법을 쓰지 않아도 당당하게 성공을 거머쥔다.", en: "Honesty is the best strategy; you seize success with dignity even without shortcuts." },
      { ko: "나의 노하우가 집대성되어 하나의 완성된 체계를 이루니 명성이 높아진다.", en: "Your know-how is integrated to form a complete system, and your reputation rises." },
      { ko: "주변의 시기 질투를 실력으로 잠재우니 진정한 실력자로 인정받는 시기이다.", en: "Silencing envy with pure skill, it's a time to be recognized as a true expert." },
      { ko: "작은 불씨가 들판을 태우듯, 나의 열정이 조직 전체를 성공으로 이끈다.", en: "As a small spark burns a field, your passion leads the entire organization to success." },
      { ko: "불가능하다고 말하던 이들이 나의 성과를 보고 찬사를 아끼지 않는구나.", en: "Those who said it was impossible now lavish praise upon seeing your achievements." },
      { ko: "나의 성실함이 보이지 않는 곳에서 빛을 발하여 뜻밖의 발탁운이 따른다.", en: "Your sincerity shines in unseen places, leading to an unexpected opportunity for selection." },
      { ko: "지치지 않는 체력과 정신력이 뒷받침되니 어떤 큰 도전도 두렵지 않도다.", en: "With tireless physical and mental strength, no great challenge is daunting." },
      { ko: "과거의 실패가 소중한 밑거름이 되어 이번에는 완벽한 성공을 일구어낸다.", en: "Past failures become valuable fertilizer, leading to perfect success this time." },
      { ko: "나의 아이디어가 특허나 저작권으로 보호받으니 부와 명예가 동시에 따른다.", en: "Your ideas are protected by patents or copyrights, bringing both wealth and honor." },
      { ko: "고생 끝에 낙이 온다는 말처럼, 오랜 인고의 시간이 화려한 결실을 맺는다.", en: "As the saying goes, joy comes after hardship; long times of patience bear brilliant fruit." },
      { ko: "포기하지 않고 걸어온 끈기가 마침내 거대한 장벽을 허물고 승리의 깃발을 꽂는다.", en: "The persistence of walking without giving up finally breaks down the huge barrier and plants the flag of victory." },
      { ko: "나의 성실함이 보증수표가 되어, 업계에서 독보적인 존재감을 인정받는 시기이다.", en: "Your sincerity becomes a guaranteed check, a time when your unrivaled presence is recognized in the industry." },
      { ko: "작은 디테일의 차이가 거대한 성공을 만드니, 나의 완벽주의가 빛을 발하리로다.", en: "Small differences in detail create huge success; your perfectionism will shine." },
      { ko: "그동안 갈고닦은 실력이 임계점을 넘었으니, 이제는 거침없이 비상할 일만 남았다.", en: "The skills you've honed have passed the critical point; now only the task of soaring remains." },
      { ko: "나의 창의적인 해법이 난제를 해결하니, 조직 내에서 대체 불가능한 인재로 우뚝 선다.", en: "Your creative solution solves a difficult problem, standing tall as an irreplaceable talent within the organization." },
      { ko: "실패를 두려워하지 않는 용기가 행운과 만나, 상상 이상의 커리어 하이를 달성한다.", en: "Courage without fear of failure meets luck, achieving a career high beyond imagination." },
      { ko: "나의 이름이 명예로운 자리에 새겨지니, 가문의 영광이자 일생의 자부심이 되리라.", en: "As your name is engraved in an honorable place, it becomes the glory of the family and the pride of a lifetime." },
      { ko: "고독한 훈련의 시간이 화려한 조명으로 바뀌는 순간, 세상의 박수갈채가 쏟아진다.", en: "The moment the time of lonely training turns into brilliant lighting, the world's applause pours out." },
      { ko: "나의 리더십이 발휘되어 팀을 승리로 이끄니, 모두가 우러러보는 지도자가 된다.", en: "Your leadership is demonstrated, leading the team to victory and becoming a leader everyone looks up to." },
      { ko: "한계를 뛰어넘는 도전 정신이 불가능을 가능케 하니, 기적의 주인공은 바로 나로다.", en: "The spirit of challenge that goes beyond limits makes the impossible possible; the protagonist of the miracle is you." },
      { ko: "나의 철저한 준비성이 기회와 맞물려, 완벽한 타이밍에 최고의 성과를 거둔다.", en: "Your thorough preparation meshes with opportunity, achieving the best results at the perfect timing." },
      { ko: "주변의 비판을 찬사로 바꾸는 역전 드라마를 쓰니, 나의 저력이 증명되는 날이다.", en: "Writing a reversal drama that turns criticism into praise; it is a day when your potential is proven." },
      { ko: "나의 연구와 노력이 특허나 저작권으로 인정받아, 지적 자산의 가치가 급상승한다.", en: "Your research and efforts are recognized as patents or copyrights, and the value of intellectual assets skyrockets." },
      { ko: "어려운 시험이나 자격증 취득에 합격의 기쁨이 있으니, 새로운 문이 활짝 열린다.", en: "There is the joy of passing a difficult exam or obtaining a license, and a new door opens wide." },
      { ko: "나의 성취가 사회적 공헌으로 이어지니, 성공을 넘어 존경받는 인물이 되도다.", en: "As your achievements lead to social contributions, you become a respected person beyond success." },
      { ko: "작은 아이디어가 구체적인 사업 모델이 되어, 시장을 흔드는 혁신을 일으킨다.", en: "A small idea becomes a concrete business model, causing innovation that shakes the market." },
      { ko: "나의 안목이 시대를 앞서가니, 트렌드를 선도하는 선구자로서 큰 명성을 얻는다.", en: "Your insight is ahead of the times; you gain great fame as a pioneer leading trends." },
      { ko: "막판 뒤집기의 명수가 되니, 불리한 상황조차 나를 돋보이게 하는 장치가 된다.", en: "Becoming a master of the last-minute turnaround, even unfavorable situations become devices that make you stand out." },
      { ko: "나의 집중력이 최고조에 달하니, 단시간에 방대한 양의 과업을 완벽히 끝낸다.", en: "Your concentration reaches its peak, perfectly finishing a huge amount of tasks in a short time." },
      { ko: "꿈꾸던 무대에 오를 기회를 잡으니, 그동안의 설움이 환희로 바뀌는 순간이다.", en: "Seizing the chance to stand on the dream stage; it's the moment when past sorrows turn into joy." },
      { ko: "나의 신념을 굽히지 않은 보람이 있어, 결국 나의 방식이 옳았음이 만천하에 드러난다.", en: "It was worth not bending your beliefs; eventually, it's revealed to the world that your way was right." },
      { ko: "경쟁자조차 나의 실력을 인정하고 고개를 숙이니, 진정한 승자의 여유를 만끽하라.", en: "Even competitors recognize your skills and bow their heads; enjoy the true winner's composure." },
      { ko: "나의 성취가 경제적 자유로 가는 든든한 발판이 되니, 일과 부를 동시에 거머쥔다.", en: "Your achievements become a solid foothold toward financial freedom, grasping both work and wealth." },
      { ko: "오늘은 협상에서 주도권을 잡는 날이니, 내가 원하는 조건을 모두 관철하게 된다.", en: "Today is a day to take the initiative in negotiations; you will carry through all the conditions you want." },
      { ko: "나의 재능이 적재적소를 만나 빛을 발하니, 일하는 즐거움이 곧 성공의 동력이다.", en: "Your talent meets the right place and shines; the joy of working is the driving force of success." },
      { ko: "거장들의 인정을 받아 나의 위상이 높아지니, 더 큰 꿈을 꿀 수 있는 기반이 마련된다.", en: "Receiving recognition from masters increases your status, laying the foundation for bigger dreams." },
      { ko: "나의 열정이 식지 않는 한 실패는 과정일 뿐이니, 오늘의 성취는 그 보상이다.", en: "As long as your passion doesn't cool, failure is just a process; today's achievement is the reward." },
      { ko: "세상의 편견을 깨고 당당히 일어서니, 나의 행보가 누군가에게는 새로운 희망이 된다.", en: "Breaking the world's prejudice and standing tall; your footsteps become a new hope for someone." },
      { ko: "나의 체력과 정신력이 조화를 이루니, 장기전에서도 결국 승리를 쟁취하는구나.", en: "Your physical and mental strength are in harmony; you eventually win even in long-term battles." },
      { ko: "오늘은 프로젝트의 화룡점정을 찍는 날이니, 완벽한 마무리로 극찬을 받는다.", en: "Today is the day to put the finishing touch on the project, receiving high praise for a perfect finish." },
      { ko: "나의 성취 뒤에 숨은 노력을 하늘이 아시니, 명예와 함께 실질적인 보너스가 따른다.", en: "As heaven knows the effort behind your achievements, a practical bonus follows with honor." },
      { ko: "끊임없는 자기계발이 결실을 맺어, 어제의 나를 뛰어넘는 놀라운 성장을 이룬다.", en: "Constant self-development bears fruit, achieving amazing growth that surpasses who you were yesterday." },
      { ko: "나의 전문성이 빛을 발하여 중요한 결정권을 쥐게 되니, 영향력이 막강해진다.", en: "Your expertise shines, and you hold important decision-making power; your influence becomes powerful." },
      { ko: "오늘은 막혔던 아이디어가 샘솟듯 터져 나오니, 창조적인 작업에 최고의 날이다.", en: "Today, blocked ideas burst out like a spring; it's the best day for creative work." },
      { ko: "나의 성취가 널리 알려져 스카우트 제의나 협력 요청이 쇄도하는 시기이다.", en: "Your achievements are widely known; it's a time when scout offers or collaboration requests flood in." },
      { ko: "어려운 고비를 넘길 때마다 나의 내공이 깊어지니, 이제는 어떤 풍파도 두렵지 않다.", en: "Every time you pass a difficult hurdle, your inner strength deepens; now no storm is frightening." },
      { ko: "나의 진심이 담긴 성과물이 대중의 마음을 사로잡으니, 선풍적인 인기를 얻는다.", en: "Your work, filled with sincerity, captures the public's heart, gaining sensational popularity." },
      { ko: "오늘은 중요한 발표나 면접에서 최고의 평가를 받으니, 앞길이 탄탄대로로다.", en: "Receiving the best evaluation in an important presentation or interview today; the path ahead is solid." },
      { ko: "나의 성취가 공동체의 이익이 되니, 많은 이들의 축복 속에 성공의 탑을 쌓는다.", en: "As your achievement benefits the community, you build a tower of success amidst many blessings." },
      { ko: "포기하고 싶을 때 한 걸음 더 나아간 용기가 오늘의 위대한 결과를 만들었다.", en: "The courage to go one step further when you wanted to give up created today's great result." },
      { ko: "나의 전략이 정확히 적중하니, 최소한의 노력으로 최대한의 효율을 거두는구나.", en: "Your strategy hits exactly; you reap maximum efficiency with minimum effort." },
      { ko: "오늘은 나의 권위가 바로 서는 날이니, 사람들의 신뢰와 복종이 자연히 따른다.", en: "Today is the day your authority is established; people's trust and obedience follow naturally." },
      { ko: "나의 성취가 기록으로 남으니, 후배들에게 귀감이 되는 역사적인 순간이다.", en: "Your achievements are recorded; it's a historical moment that serves as a model for juniors." },
      { ko: "어두운 밤을 지나 찬란한 새벽을 맞이하듯, 고난 끝에 찾아온 성공이 눈부시다.", en: "Like meeting a brilliant dawn after a dark night, the success that came after hardship is dazzling." },
      { ko: "나의 소신이 세상과 통하니, 나만의 독특한 스타일이 새로운 기준이 된다.", en: "Your convictions resonate with the world; your unique style becomes a new standard." },
      { ko: "오늘은 지혜로운 멘토의 조언이 나의 성취를 앞당기는 기폭제가 되어준다.", en: "Today, a wise mentor's advice becomes a catalyst that accelerates your achievement." },
      { ko: "나의 열정이 주위를 전염시키니, 모두가 합심하여 불가능한 목표를 달성한다.", en: "Your passion infects those around you; everyone works together to achieve an impossible goal." },
      { ko: "오늘은 나의 직감이 비즈니스에서 큰 승리를 가져다주니, 나를 믿고 밀어붙여라.", en: "Your intuition brings a big victory in business today; trust yourself and push forward." },
      { ko: "나의 성취가 가족에게 기쁨을 주니, 집안 전체에 웃음꽃과 자랑이 끊이지 않는다.", en: "Your achievement brings joy to the family; laughter and pride never cease throughout the house." },
      { ko: "오늘의 성취는 시작일 뿐이니, 더 높은 정상을 향해 신발 끈을 다시 묶어라.", en: "Today's achievement is just the beginning; tie your shoelaces again for a higher peak." },
      ],
    "행운운": [
      { ko: "생각지 못한 곳에서 행운의 열쇠를 발견하니, 닫혔던 문이 절로 열리는구나.", en: "Finding the key to luck in an unexpected place, the closed door opens on its own." },
      { ko: "길을 걷다 보석을 줍는 형국이라, 일상 속에 숨겨진 큰 기쁨을 만끽하리라.", en: "It is like picking up a gem while walking; enjoy the great joy hidden in daily life." },
      { ko: "동쪽에서 불어오는 상서로운 바람이 나쁜 기운을 몰아내고 복을 가져온다.", en: "The auspicious wind blowing from the east drives away bad energy and brings fortune." },
      { ko: "우연히 참여한 일에서 뜻밖의 큰 수확을 거두니, 하늘이 나를 돕는 시기이다.", en: "Reaping an unexpected harvest from a chance involvement; it is a time when heaven helps." },
      { ko: "나의 발걸음이 닿는 곳마다 행운이 따라붙으니, 매사가 즐겁고 경이롭도다.", en: "Luck follows wherever your steps reach, making everything joyful and wondrous." },
      { ko: "잃어버렸던 소중한 물건을 되찾거나, 잊고 있던 행운이 다시 찾아올 징조이다.", en: "A sign of recovering a lost precious item or a forgotten luck returning to you." },
      { ko: "오늘은 가는 곳마다 나를 반겨주는 이가 가득하니, 세상이 나의 편인 듯하다.", en: "Everywhere you go today is filled with people welcoming you; it feels as if the world is on your side." },
      { ko: "작은 호의가 눈덩이처럼 불어나 큰 행운으로 돌아오니, 마음껏 미소 지어라.", en: "A small favor snowballs into great luck and returns to you; smile as much as you want." },
      { ko: "깜짝 놀랄 만한 즐거운 소식이 문을 두드리니, 집안에 웃음소리가 끊이지 않는다.", en: "Surprising and joyful news knocks on your door, and laughter never ceases in the house." },
      { ko: "운명의 수레바퀴가 나에게 유리하게 돌아가니, 모든 우연이 나를 위해 존재한다.", en: "The wheel of fortune turns in your favor; every coincidence exists for you." },
      { ko: "평소 가보고 싶던 곳에서 뜻밖의 인연과 행운이 기다리고 있으니 움직여라.", en: "Luck and an unexpected connection await in a place you've always wanted to go, so move." },
      { ko: "나의 긍정적인 에너지가 행운을 끌어당기니, 웃음 끝에 복이 넝쿨째 들어온다.", en: "Your positive energy attracts luck; fortune comes in bunches at the end of laughter." },
      { ko: "막혔던 운의 흐름이 물꼬를 트듯 풀리니, 매사가 순조롭게 돌아가기 시작한다.", en: "The blocked flow of luck opens up like a waterway, and everything begins to run smoothly." },
      { ko: "무심코 던진 제안이 큰 행운의 불씨가 되어 나의 일상을 풍요롭게 하리라.", en: "A casual suggestion becomes a spark of great luck, enriching your daily life." },
      { ko: "하늘의 기운이 나를 감싸니, 위태로운 순간조차 행운으로 바뀌는 기적이 일어난다.", en: "The energy of heaven surrounds you; a miracle happens where even risky moments turn into luck." },
      { ko: "작은 선행이 보이지 않는 곳에서 복이 되어 돌아오니, 마음이 훈훈해지는구나.", en: "Small good deeds return as blessings from unseen places, warming your heart." },
      { ko: "나의 안목이 빛을 발하여 숨겨진 가치를 발견하니, 횡재수가 따르는 시기이다.", en: "Your insight shines, discovering hidden value; it is a time when a windfall follows." },
      { ko: "꿈자리가 상서로우니 조상님의 보살핌 속에 만사가 형통할 징조로다.", en: "The dream is auspicious; it's a sign that everything will go well under the care of ancestors." },
      { ko: "어려운 고비마다 구원의 손길이 나타나니, 나의 운명이 나를 돕고 있다.", en: "A helping hand appears at every difficult hurdle; your destiny is helping you." },
      { ko: "오늘의 모든 우연은 나를 위한 선물인 듯, 바라는 것마다 착착 이루어진다.", en: "Every coincidence today feels like a gift for you; everything you wish for comes true perfectly." },
      { ko: "평범한 일상 속에 숨겨진 행운의 조각들이 모여 커다란 기쁨을 만들어낸다.", en: "Hidden pieces of luck in ordinary daily life gather to create a great joy." },
      { ko: "나의 직감이 예리하게 작용하니, 선택하는 것마다 행운의 길로 이어지는구나.", en: "Your intuition works keenly, so every choice you make leads to a path of luck." },
      { ko: "오랜 시간 기다려온 기분 좋은 소식이 마침내 나에게로 날아오는 시기이다.", en: "It is a time when the pleasant news you've long waited for finally flies to you." },
      { ko: "주변의 밝은 기운이 나를 감싸니, 나쁜 액운은 물러가고 복된 일만 가득하다.", en: "Bright energy around you surrounds you, so bad luck retreats and only blessed things are full." },
      { ko: "작은 변화를 시도해 보라. 그 사소한 시작이 거대한 행운의 물결을 가져오리라.", en: "Try a small change. That minor start will bring a huge wave of luck." },
      { ko: "뜻밖의 장소에서 만난 사람이 나에게 황금 같은 기회를 전해주는 행운이 있다.", en: "There is the luck of a person met in an unexpected place delivering a golden opportunity." },
      { ko: "오늘은 하늘의 보살핌이 지극하니, 어떤 어려움도 마법처럼 풀려나갈 것이다.", en: "Heaven's care is extreme today, so any difficulties will be solved like magic." },
      { ko: "마음속에 품었던 긍정의 씨앗이 행운의 꽃으로 피어나니 향기가 진동하도다.", en: "The seeds of positivity held in your heart bloom into flowers of luck, sending out a rich fragrance." },
      { ko: "나를 돕는 보이지 않는 손길이 느껴지니, 모든 우연이 나를 향해 웃어준다.", en: "Feeling an unseen hand helping you, every coincidence smiles toward you." },
      { ko: "잃어버렸던 활력을 되찾으니, 건강한 몸에 깃든 행운이 빛을 발하는구나.", en: "Recovering lost vitality, the luck dwelling in a healthy body shines brightly." },
      { ko: "먹구름이 걷히고 찬란한 태양이 비추듯, 힘든 시간을 보상받는 행운이 온다.", en: "As dark clouds lift and the brilliant sun shines, luck comes to reward the hard times." },
      { ko: "가벼운 마음으로 나선 길에서 평생의 기억에 남을 소중한 인연을 만난다.", en: "On a path taken with a light heart, you meet a precious connection that will last a lifetime." },
      { ko: "나의 진심이 하늘에 닿아, 도저히 풀리지 않던 매듭이 기적처럼 풀리리라.", en: "Your sincerity reaches heaven, and the knot that couldn't be untied will loosen like a miracle." },
      { ko: "주머니 속의 송곳처럼 나의 재능이 드러나니, 행운의 기회가 나를 먼저 찾아온다.", en: "Like an awl in a pocket, your talent reveals itself, and lucky opportunities find you first." },
      { ko: "오늘은 작은 내기나 당첨운이 따르는 날이니, 소소한 즐거움을 기대해도 좋다.", en: "Today is a day for small bets or winning luck, so you can expect minor joys." },
      { ko: "나의 성실함이 복의 근원이 되어, 예상치 못한 장소에서 보상을 받게 되도다.", en: "Your sincerity becomes the source of fortune, and you receive rewards in unexpected places." },
      { ko: "지나가는 사람의 말 한마디가 나에게는 천금 같은 성공의 힌트가 되는구나.", en: "A single word from a passerby becomes a hint for success as valuable as a thousand pieces of gold." },
      { ko: "마음의 창을 활짝 여니, 세상의 모든 좋은 기운이 나에게로 스며든다.", en: "Opening the window of your heart wide, all the good energy in the world seeps into you." },
      { ko: "나의 이름이 널리 알려지고 명예가 따르니, 행운의 여신이 나를 보고 웃는다.", en: "As your name becomes widely known and honor follows, the Goddess of Luck smiles at you." },
      { ko: "한결같은 마음으로 기다린 보람이 있어, 마침내 황금빛 행운이 문 앞에 당도했다.", en: "It was worth waiting with a consistent heart; finally, golden luck has arrived at your door." },
      { ko: "길운이 나를 감싸니, 평소 어렵게만 느껴지던 일들이 술술 풀리는 시기이다.", en: "As good luck surrounds you, it's a time when things that usually felt difficult unravel easily." },
      { ko: "나의 맑은 안색이 행운을 부르니, 거울 속의 미소가 곧 복의 시작이로다.", en: "Your clear complexion calls for luck; the smile in the mirror is the beginning of fortune." },
      { ko: "낡은 것을 버리고 새것을 취하니, 주변 환경의 변화가 큰 행운을 몰고 온다.", en: "Discarding the old and taking the new, changes in your surroundings bring great luck." },
      { ko: "나의 인내심이 결실을 맺어, 생각보다 훨씬 큰 행운의 보답이 돌아오는구나.", en: "Your patience bears fruit, and a much larger reward of luck than expected returns." },
      { ko: "오늘은 동서남북 어느 방향으로 가도 나를 도와줄 행운의 조력자가 있다.", en: "No matter which direction you go today—east, west, south, or north—there is a lucky helper." },
      { ko: "뜻밖의 편지나 메시지가 행운의 전령이 되어, 가슴 설레는 기쁨을 선사하리라.", en: "An unexpected letter or message becomes a messenger of luck, bringing heart-fluttering joy." },
      { ko: "나의 창의적인 생각이 세상을 밝히니, 행운이 나를 따라다니며 빛을 비춘다.", en: "Your creative thoughts brighten the world, and luck follows you, shining a light." },
      { ko: "막다른 골목이라 생각한 곳에서 새로운 길이 열리니, 이것이 진정한 천운이로다.", en: "A new path opens where you thought it was a dead end; this is true heavenly luck." },
      { ko: "작은 씨앗 하나가 거목이 되듯, 오늘의 사소한 행운이 미래의 큰 자산이 된다.", en: "Just as a small seed becomes a giant tree, today's minor luck becomes a great asset for the future." },
      { ko: "나의 운세가 절정에 달했으니, 망설이지 말고 행운의 기운을 마음껏 누려라.", en: "Your fortune has reached its peak; do not hesitate and enjoy the energy of luck to your heart's content." },
      { ko: "길가에 핀 이름 모를 꽃에서도 행운의 향기가 나니, 오늘은 기분 좋은 우연이 겹친다.", en: "Even an unnamed flower by the road smells of luck; pleasant coincidences overlap today." },
      { ko: "나의 맑은 기운이 복을 부르니, 가는 곳마다 나를 반기는 미소가 가득하도다.", en: "Your clear energy calls for fortune; everywhere you go is filled with welcoming smiles." },
      { ko: "하늘이 무너져도 솟아날 구멍이 있듯, 절박한 순간에 기적 같은 천운이 나를 돕는다.", en: "As if there's a way out even if the sky falls, miracle-like luck helps you in desperate moments." },
      { ko: "우연히 집어 든 책 한 권 속에 인생을 바꿀 행운의 열쇠가 숨겨져 있다.", en: "Within a book picked up by chance, a key to luck that will change your life is hidden." },
      { ko: "나의 긍정적인 말 한마디가 행운의 부메랑이 되어 더 큰 복으로 돌아오리라.", en: "Your positive word becomes a boomerang of luck and returns as a greater blessing." },
      { ko: "꿈속에서 본 상서로운 징조가 현실로 나타나니, 오늘 하루는 모든 일이 신비롭다.", en: "Auspicious signs seen in a dream manifest in reality; everything today is mysterious." },
      { ko: "나를 괴롭히던 액운이 물러가고, 그 자리에 찬란한 행운의 햇살이 비치기 시작한다.", en: "The bad luck that troubled you retreats, and the brilliant sunlight of luck begins to shine." },
      { ko: "뜻밖의 선물이나 초대를 받게 되니, 사람들과 나누는 즐거움 속에 행운이 깃든다.", en: "Receiving an unexpected gift or invitation; luck dwells in the joy of sharing with others." },
      { ko: "오늘은 나의 직감이 100% 적중하는 날이니, 마음이 시키는 대로 움직여도 좋다.", en: "Today is a day when your intuition hits 100%, so you may move as your heart leads." },
      { ko: "비 온 뒤 땅이 굳어지듯, 고난 뒤에 찾아온 행운은 결코 나를 떠나지 않으리라.", en: "As the ground hardens after rain, the luck that comes after hardship will never leave you." },
      { ko: "나의 주변 환경이 나를 돕는 방향으로 급변하니, 운명의 수레바퀴가 나를 향해 웃는다.", en: "Your surroundings change rapidly to help you; the wheel of fortune smiles at you." },
      { ko: "평소 무심코 지나쳤던 장소가 오늘은 나에게 보물창고 같은 행운을 선사한다.", en: "A place you usually passed by mindlessly presents you with luck like a treasure house today." },
      { ko: "나의 선행이 보이지 않는 곳에서 쌓여, 오늘 커다란 행운의 결실로 나타나도다.", en: "Your good deeds accumulate in unseen places, appearing as a great fruit of luck today." },
      { ko: "어려운 문제의 해답을 우연히 듣게 되니, 막혔던 가슴이 시원하게 뚫리는구나.", en: "Happening to hear the answer to a difficult problem, your blocked chest opens refreshingly." },
      { ko: "오늘은 모든 신호등이 초록불인 듯, 나의 앞길을 막는 장애물이 하나도 없다.", en: "As if all traffic lights are green today, there are no obstacles blocking your path." },
      { ko: "나의 밝은 웃음소리가 행운의 요정을 불러오니, 집안에 경사스러운 일이 가득하다.", en: "Your bright laughter calls the fairy of luck; auspicious events are full in the house." },
      { ko: "우연히 참여한 모임에서 평생의 은인을 만나게 되는 천재일우의 기회가 온다.", en: "A once-in-a-lifetime opportunity comes to meet a lifelong benefactor at a gathering you joined by chance." },
      { ko: "나의 낡은 습관을 버리는 순간, 새로운 행운이 그 빈자리를 가득 채우게 되리라.", en: "The moment you discard your old habits, new luck will fill that empty space." },
      { ko: "오늘은 복권이나 작은 경품에도 운이 따르니, 가벼운 마음으로 행운을 시험해 보라.", en: "Luck follows even in lotteries or small prizes today; test your luck with a light heart." },
      { ko: "나의 겸손한 태도가 복을 부르니, 높이 오를수록 행운의 깊이도 깊어지는구나.", en: "Your humble attitude calls for fortune; the higher you rise, the deeper the luck becomes." },
      { ko: "잃어버린 줄 알았던 소중한 인연이 다시 연락해 오니, 끊겼던 복운이 다시 이어진다.", en: "A precious connection thought to be lost contacts you again; the broken fortune is reconnected." },
      { ko: "오늘은 나의 목소리에 힘이 실리니, 제안하는 것마다 행운의 승낙을 받게 된다.", en: "Power is added to your voice today; every proposal you make receives a lucky acceptance." },
      { ko: "나의 창의적인 발상이 행운과 만나, 세상이 깜짝 놀랄 만한 기적을 만들어낸다.", en: "Your creative idea meets luck, creating a miracle that will surprise the world." },
      { ko: "길을 잃었다고 생각한 순간, 더 아름다운 풍경과 더 큰 행운을 마주하게 되도다.", en: "The moment you think you are lost, you encounter more beautiful scenery and greater luck." },
      { ko: "나의 건강이 회복되니, 활기찬 몸을 따라 행운의 기운도 힘차게 솟구친다.", en: "As your health recovers, the energy of luck soars vigorously along with your lively body." },
      { ko: "오늘은 동서남북 어느 곳을 보아도 나를 돕는 기운이 가득하니 두려울 것이 없다.", en: "Looking in any direction—north, south, east, or west—there is full energy helping you; have no fear." },
      { ko: "나의 인내심이 임계점을 지나니, 이제부터는 행운의 열매를 수확할 일만 남았다.", en: "Your patience has passed the critical point; now only the task of harvesting the fruit of luck remains." },
      { ko: "뜻밖의 장소에서 만난 아이의 순수한 말 한마디가 행운의 예언이 되어 돌아온다.", en: "A pure word from a child met in an unexpected place returns as a prophecy of luck." },
      { ko: "나의 성실함이 쌓여 운의 흐름을 바꾸었으니, 이제는 가만히 있어도 복이 찾아온다.", en: "Your diligence has accumulated and changed the flow of luck; now fortune finds you even if you stay still." },
      { ko: "오늘은 옷차림에 신경을 써보라. 나의 매력이 행운을 당기는 강력한 자석이 된다.", en: "Pay attention to your attire today. Your charm becomes a powerful magnet attracting luck." },
      { ko: "나의 진심 어린 눈물이 액운을 씻어내고, 그 자리에 행운의 새싹이 돋아나는구나.", en: "Your sincere tears wash away bad luck, and the sprouts of luck grow in that place." },
      { ko: "우연히 들른 상점의 주인이 나에게 특별한 행운의 소식을 전해주는 시기이다.", en: "It is a time when the owner of a store you happened to stop by delivers special lucky news to you." },
      { ko: "나의 관대한 마음이 복을 키우니, 타인을 용서할 때 더 큰 행운이 나에게 온다.", en: "Your generous heart grows fortune; greater luck comes to you when you forgive others." },
      { ko: "오늘은 머물러 있기보다 움직이는 것이 좋으니, 발걸음마다 행운이 밟히리라.", en: "It is better to move than to stay still today; luck will be stepped on with every step." },
      { ko: "나의 이름이 좋은 일로 사람들 입에 오르내리니, 행운의 여신이 나를 보호한다.", en: "As your name is mentioned for good things, the Goddess of Luck protects you." },
      { ko: "어두운 밤을 비추는 등대처럼, 나의 소중한 친구가 행운의 길잡이가 되어준다.", en: "Like a lighthouse shining through the dark night, your precious friend becomes a guide to luck." },
      { ko: "나의 열정이 식지 않으니, 하늘도 감동하여 마르지 않는 행운의 샘물을 부어준다.", en: "Since your passion does not cool, heaven is moved and pours a never-drying spring of luck." },
      { ko: "오늘은 거절할 수 없는 달콤한 행운의 제안이 들어오니, 과감하게 승낙하라.", en: "A sweet lucky proposal that cannot be refused comes today; accept it boldly." },
      { ko: "나의 소박한 소원이 뜻밖의 거대한 행운으로 치환되어 돌아오는 신비한 날이다.", en: "It is a mysterious day when your simple wish is substituted for an unexpected huge luck." },
      { ko: "오늘은 나의 편이 많아지는 날이니, 경쟁 속에서도 나만 행운의 승자가 된다.", en: "Today is a day when you gain many allies; even in competition, only you become the lucky winner." },
      { ko: "나의 예지몽이 현실에서 그대로 적중하니, 행운을 미리 준비할 수 있게 되도다.", en: "Your precognitive dream hits exactly in reality, allowing you to prepare for luck in advance." },
      { ko: "가벼운 여행길에서 만난 낯선 이가 나에게 천금 같은 행운의 기회를 준다.", en: "A stranger met on a light trip gives you a lucky opportunity as valuable as gold." },
      { ko: "나의 성품이 향기로운 꽃과 같으니, 나비가 모여들 듯 행운이 쉼 없이 찾아온다.", en: "Your character is like a fragrant flower; luck finds you restlessly as butterflies gather." },
      { ko: "오늘은 지갑을 열 때마다 더 큰 행운이 들어오니, 기분 좋게 베풀어도 좋다.", en: "Greater luck enters every time you open your wallet today, so it's okay to give pleasantly." },
      { ko: "나의 오랜 노력이 드디어 운의 때를 만났으니, 이제는 거둘 일만 남은 시기이다.", en: "Your long effort has finally met the time of luck; it is now a time when only harvesting remains." },
      { ko: "오늘은 나의 직감이 보물 지도가 되니, 첫 느낌을 믿고 과감하게 추진하라.", en: "Your intuition becomes a treasure map today; trust your first feeling and push forward boldly." },
      { ko: "나의 긍정 에너지가 주변을 정화하니, 나쁜 기운은 사라지고 행운만 머문다.", en: "Your positive energy purifies the surroundings; bad energy disappears and only luck stays." },
      { ko: "생각지 못한 환급금이나 보상금이 들어오는 운이니, 통장의 숫자가 나를 웃게 한다.", en: "Destined for unexpected refunds or compensation; the numbers in the bank account make you smile." },
      { ko: "나의 작은 배려가 눈덩이처럼 불어나, 오늘은 감당하기 힘든 큰 복으로 돌아온다.", en: "Your small consideration snowballs and returns today as a big blessing hard to handle." },
      { ko: "나의 운세가 만개한 꽃처럼 화려하니, 세상의 모든 행운이 나를 위해 축배를 든다.", en: "Your fortune is as brilliant as a flower in full bloom; all the luck in the world toasts for you." },/* 데이터 삽입 예정 */ ],
    "소망운": [
      { ko: "오랫동안 가슴속에 품어온 간절한 기도가 마침내 하늘의 문을 두드린다.", en: "The earnest prayer kept in your heart for a long time finally knocks on heaven's door." },
      { ko: "간절히 원하면 온 우주가 돕는다는 말처럼, 나의 소망이 현실로 다가온다.", en: "As the saying goes, if you want it earnestly, the universe helps; your wish nears reality." },
      { ko: "불가능해 보이던 목표가 구체적인 계획으로 바뀌니, 성취의 서광이 비친다.", en: "The goal that seemed impossible turns into a concrete plan, and the dawn of achievement shines." },
      { ko: "나의 진심 어린 바람이 귀인의 마음을 움직여, 큰 조력자를 얻게 되리라.", en: "Your sincere wish moves the heart of a noble person, leading you to gain a great helper." },
      { ko: "작은 소망들이 하나둘씩 결실을 맺으니, 큰 꿈을 향한 발걸음이 가벼워진다.", en: "As small wishes bear fruit one by one, your steps toward a big dream become lighter." },
      { ko: "어두운 밤하늘의 북극성처럼, 나의 꿈이 나아가야 할 길을 선명하게 비춘다.", en: "Like the North Star in the dark night sky, your dream clearly lights the path to follow." },
      { ko: "뿌린 대로 거두는 법이니, 그동안의 인내가 달콤한 소망의 열매로 돌아온다.", en: "As you reap what you sow, your past patience returns as the sweet fruit of your wishes." },
      { ko: "마음속에 그린 설계도대로 인생이 흘러가니, 생각하는 대로 이루어지는구나.", en: "Life flows according to the blueprint drawn in your heart; it happens as you think." },
      { ko: "나의 열망이 임계점에 도달했으니, 이제 곧 기적 같은 변화가 시작되도다.", en: "Your longing has reached its critical point; now, a miracle-like change is about to begin." },
      { ko: "망설임은 버리고 확신을 가져라. 나의 소망은 이미 이루어질 준비를 마쳤다.", en: "Cast away hesitation and have confidence. Your wish is already prepared to come true." },
      { ko: "포기하려던 순간에 다시 타오르는 불꽃처럼, 나의 꿈이 새 생명을 얻는다.", en: "Like a flame burning again at the moment of giving up, your dream gains new life." },
      { ko: "나의 간절함이 주변 사람들을 감동시키니, 온 세상이 나의 성공을 응원한다.", en: "Your earnestness moves the people around you, and the whole world cheers for your success." },
      { ko: "작은 물줄기가 모여 강을 이루듯, 매일의 작은 실천이 큰 소망을 완성하리라.", en: "As small streams gather to form a river, daily small actions will complete a great wish." },
      { ko: "가슴속의 열정이 나침반이 되어, 혼란 속에서도 정확한 방향을 찾아가는구나.", en: "The passion in your heart becomes a compass, finding the exact direction even in confusion." },
      { ko: "뿌연 안개가 걷히고 선명한 풍경이 드러나듯, 나의 비전이 현실로 구체화된다.", en: "As the thick fog lifts and a clear landscape appears, your vision is materialized into reality." },
      { ko: "나의 소망이 때를 만났으니, 거침없이 나아가 최고의 자리에 오르게 되도다.", en: "Your wish has met its time; go forward without hesitation and reach the top position." },
      { ko: "지성이면 감천이라, 나의 정성이 하늘을 움직여 바라는 바를 얻게 될 시기이다.", en: "Sincerity moves heaven; it is time to obtain what you desire through your devotion." },
      { ko: "어제의 꿈이 오늘의 현실이 되니, 나의 상상력이 인생의 지도가 되는구나.", en: "Yesterday's dream becomes today's reality; your imagination becomes the map of your life." },
      { ko: "나의 가치를 알아주는 사람들을 만나니, 소망을 향한 여정이 외롭지 않으리라.", en: "Meeting people who recognize your value, the journey toward your wish will not be lonely." },
      { ko: "기회는 준비된 자의 편이니, 나의 소망을 담을 그릇을 미리 준비해 두어라.", en: "Opportunity is on the side of the prepared; prepare the vessel to hold your wishes in advance." },
      { ko: "길고 긴 기다림이 헛되지 않았으니, 인내의 시간이 화려한 영광으로 돌아온다.", en: "Your long wait was not in vain; the time of patience returns as brilliant glory." },
      { ko: "나의 간절한 소망이 기적의 씨앗이 되어, 척박한 땅에서도 꽃을 피워내는구나.", en: "Your earnest wish becomes the seed of a miracle, blooming even in barren land." },
      { ko: "혼자만의 꿈이 아닌 만인의 응원을 받는 소망이니, 그 성취가 더욱 찬란하도다.", en: "It is a wish supported by everyone, not just a lonely dream, so its achievement is even more brilliant." },
      { ko: "나의 신념이 바위처럼 단단하니, 어떤 장애물도 나의 소망을 가로막지 못하리라.", en: "Your belief is as solid as a rock; no obstacle can block your wish." },
      { ko: "뿌린 열정만큼 거두는 시기이니, 내가 꿈꾸던 미래가 눈앞에 펼쳐지기 시작한다.", en: "It is a time to reap as much passion as you've sown; the future you dreamed of begins to unfold." },
      { ko: "나의 소망을 향한 진심이 하늘을 감동시켜, 예상치 못한 귀인이 길을 열어준다.", en: "Your sincerity toward your wish moves heaven, and an unexpected noble person opens the path." },
      { ko: "작은 성공의 기쁨이 모여 큰 소망의 원동력이 되니, 오늘을 마음껏 축복하라.", en: "The joy of small successes gathers to become the driving force of a great wish; bless today to your heart's content." },
      { ko: "나의 무궁무진한 잠재력이 깨어나니, 소망하던 일이 현실이 되는 것은 시간문제로다.", en: "Your infinite potential awakens; it is only a matter of time before your wish becomes reality." },
      { ko: "어둠 속에서 길을 찾는 여행자에게 등불이 나타나듯, 명확한 해결책이 제시된다.", en: "Just as a lamp appears to a traveler finding their way in the dark, a clear solution is presented." },
      { ko: "나의 순수한 바람이 세상에 선한 영향력을 끼치니, 부와 명예가 절로 따라온다.", en: "As your pure wish exerts a good influence on the world, wealth and honor naturally follow." },
      { ko: "간절히 바랐던 소식이 먼 곳에서 들려오니, 마음속의 응어리가 시원하게 풀린다.", en: "Long-awaited news arrives from afar, and the knot in your heart is refreshingly untied." },
      { ko: "나의 소망이 구체화될수록 환경도 그에 맞춰 변하니, 만사가 나를 돕는 형국이다.", en: "As your wish takes shape, the environment changes accordingly; everything is in a state of helping you." },
      { ko: "작은 물방울이 모여 바다를 이루듯, 나의 끈기가 거대한 소망을 현실로 만든다.", en: "As small drops of water gather to form an ocean, your persistence turns a huge wish into reality." },
      { ko: "나의 순수한 열망이 하늘의 운때와 맞물리니, 상상 이상의 결과가 나를 기다린다.", en: "Your pure desire meshes with heaven's timing, and results beyond imagination await you." },
      { ko: "포기하지 않고 걸어온 길 끝에, 내가 꿈꾸던 낙원이 그 모습을 드러내기 시작한다.", en: "At the end of the path walked without giving up, the paradise you dreamed of begins to reveal itself." },
      { ko: "나의 이름이 빛나는 순간이 다가오니, 소망하던 명예가 나를 따라오도다.", en: "The moment for your name to shine is approaching, and the desired honor follows you." },
      { ko: "주변의 시기 질투를 이겨내고 얻은 성취이니, 나의 소망이 더욱 값지고 견고하다.", en: "Since it is an achievement won over envy, your wish is even more precious and solid." },
      { ko: "마음의 평화가 소망의 근원이니, 평온함 속에 머물 때 기적 같은 일이 일어난다.", en: "Peace of mind is the source of wishes; miracle-like things happen when you stay in tranquility." },
      { ko: "나의 소망이 타인에게도 기쁨이 되니, 축복 속에 더 큰 성공이 찾아오리라.", en: "As your wish brings joy to others, even greater success will come amidst blessings." },
      { ko: "오랫동안 공들여 쌓은 공든 탑이 무너지지 않고 마침내 하늘에 닿는구나.", en: "The tower built with long-standing effort does not crumble and finally reaches the sky." },
      { ko: "길운이 문턱을 넘었으니, 이제 소망하던 바를 손에 거머쥘 일만 남았도다.", en: "Good luck has crossed the threshold; now only the task of grasping what you wished for remains." },
      { ko: "나의 진정성이 빛을 발하여, 닫혀있던 행운의 문이 활짝 열리는 시기이다.", en: "Your sincerity shines, and it is a time when the closed door of luck opens wide." },
      { ko: "작은 소망이 씨앗이 되어 거대한 숲을 이루니, 나의 삶이 풍요로움으로 가득하다.", en: "A small wish becomes a seed and forms a huge forest; your life is full of abundance." },
      { ko: "주변의 모든 이들이 나의 성공을 도우니, 소망하던 일이 순풍에 돛 단 듯 풀린다.", en: "Everyone around you helps your success; what you wished for unravels like a boat with a tailwind." },
      { ko: "나의 확신이 현실을 바꾸는 동력이 되어, 꿈꾸던 미래가 성큼 다가왔도다.", en: "Your conviction becomes the power to change reality; the future you dreamed of has approached rapidly." },
      { ko: "어려운 고난 끝에 얻은 소망의 결실이라, 그 가치가 무엇보다 소중하고 영롱하다.", en: "The fruit of a wish obtained after difficult hardships; its value is more precious and brilliant than anything." },
      { ko: "나의 선한 의지가 하늘을 움직여, 바라던 보상 그 이상의 축복을 받게 되리라.", en: "Your good will moves heaven, and you will receive blessings beyond the compensation you hoped for." },
      { ko: "오늘의 마침표는 내일의 새로운 시작이니, 소망을 이룬 뒤 더 큰 세상을 향해 나아가라.", en: "Today's period is tomorrow's new beginning; after achieving your wish, move toward a larger world." },
      { ko: "세상이 나의 뜻을 따르니, 마음먹은 대로 모든 일이 형통하게 흐르는구나.", en: "The world follows your will, so everything flows prosperously as you intended." },
      { ko: "나의 소망이 마침내 찬란한 현실이 되었으니, 이 기쁨을 세상과 함께 나누어라.", en: "Your wish has finally become a brilliant reality; share this joy with the world." },
      { ko: "마음속 깊이 간직한 꿈이 현실의 문턱을 넘으니, 기적이 일상이 되는 시기이다.", en: "The dream kept deep in your heart crosses the threshold of reality; it's a time when miracles become daily life." },
      { ko: "나의 간절함이 보이지 않는 길을 만들어내니, 불가능은 단지 수식어일 뿐이로다.", en: "Your earnestness creates an invisible path; impossible is merely an adjective." },
      { ko: "작은 희망의 불씨가 거대한 열정의 불꽃이 되어, 나의 미래를 환히 밝히는구나.", en: "A small spark of hope becomes a giant flame of passion, brightly lighting your future." },
      { ko: "세상이 안 된다고 말할 때 끝까지 믿음을 지킨 보람이 있어, 드디어 소망을 이룬다.", en: "It was worth keeping faith until the end when the world said no; you finally achieve your wish." },
      { ko: "나의 순수한 기도가 하늘의 마음을 움직이니, 예상치 못한 방법으로 응답이 온다.", en: "Your pure prayer moves the heart of heaven, and an answer comes in an unexpected way." },
      { ko: "꿈꾸던 미래의 퍼즐 조각들이 하나둘 맞춰지니, 완벽한 풍경이 눈앞에 펼쳐진다.", en: "The puzzle pieces of the dreamed future fit together one by one, unfolding a perfect landscape." },
      { ko: "나의 소망이 타인의 삶에도 빛이 되니, 축복 속에 더 큰 꿈을 향해 나아가도다.", en: "As your wish becomes a light in the lives of others, you move toward a bigger dream amidst blessings." },
      { ko: "지나온 고통의 시간이 소망의 자양분이 되어, 가장 아름다운 꽃을 피우는구나.", en: "The time of past pain becomes the nourishment for your wish, blooming the most beautiful flower." },
      { ko: "나의 확신이 주변을 변화시키니, 모두가 나의 꿈을 돕는 든든한 아군이 된다.", en: "Your conviction changes your surroundings; everyone becomes a strong ally helping your dream." },
      { ko: "오늘은 나의 간절한 바람이 운명의 흐름을 바꾸는 결정적인 전환점이 되는 날이다.", en: "Today is the day your earnest desire becomes a decisive turning point in the flow of fate." },
      { ko: "나의 소망이 때를 기다려 무르익었으니, 이제는 손을 뻗어 결실을 거머쥐어라.", en: "Your wish has ripened waiting for its time; now reach out and grasp the fruit." },
      { ko: "어두운 밤이 길수록 새벽은 눈부시듯, 기다림 끝에 찾아온 소망은 찬란하기 그지없다.", en: "As the dawn is dazzling the longer the dark night, the wish that came after waiting is beyond brilliant." },
      { ko: "나의 이름으로 세상을 이롭게 하겠다는 소망이 큰 부와 명예를 동시에 불러온다.", en: "The wish to benefit the world in your name brings both great wealth and honor simultaneously." },
      { ko: "오늘은 마음속에 소망의 설계도를 다시 그려보라. 생각하는 대로 현실이 되리라.", en: "Redraw the blueprint of your wish in your heart today. It will become reality as you think." },
      { ko: "나의 열망이 임계점을 돌파하니, 막혔던 운의 흐름이 소망을 향해 쏟아져 들어온다.", en: "Your aspiration breaks through the critical point; the blocked flow of luck pours in toward your wish." },
      { ko: "꿈을 포기하지 않는 자에게만 허락된 특별한 선물이 오늘 나의 품으로 찾아온다.", en: "A special gift allowed only to those who do not give up on their dreams finds its way into your arms today." },
      { ko: "나의 작은 선행들이 소망을 이루는 징검다리가 되어, 나를 성취의 땅으로 인도한다.", en: "Your small good deeds become stepping stones to fulfill your wish, leading you to the land of achievement." },
      { ko: "오늘은 소망하던 귀인과 극적인 만남이 있으니, 나의 비전을 당당히 공유하라.", en: "There is a dramatic meeting with the desired noble person today; share your vision confidently." },
      { ko: "나의 잠재력이 소망이라는 목표를 만나 폭발하니, 한계를 모르는 성장이 시작된다.", en: "Your potential explodes upon meeting the goal of a wish; growth that knows no limits begins." },
      { ko: "포기하려던 마음을 다잡은 순간, 소망의 신이 나에게 마지막 승리의 열쇠를 건넨다.", en: "The moment you pull yourself together after wanting to give up, the god of wishes hands you the final key to victory." },
      { ko: "나의 소망이 우주의 질서와 일치하니, 모든 자연의 이치가 나를 돕는 형국이다.", en: "Your wish matches the order of the universe; all laws of nature are in a state of helping you." },
      { ko: "오늘은 오랫동안 그리워하던 목표가 손에 잡힐 듯 가까워진 것을 느끼는 날이다.", en: "Today is the day you feel the long-missed goal has become close enough to grasp." },
      { ko: "나의 신념이 소망의 등불이 되어, 거친 풍랑 속에서도 나를 안전하게 인도하도다.", en: "Your belief becomes the lamp of your wish, safely guiding you even through rough storms." },
      { ko: "작은 물방울이 바위에 구멍을 내듯, 나의 꾸준한 염원이 기적을 현실로 만든다.", en: "Just as small drops of water drill a hole in a rock, your steady longing turns miracles into reality." },
      { ko: "나의 소망이 씨앗이 되어 풍요로운 숲을 이루니, 대대손손 그 덕을 입게 되리라.", en: "Your wish becomes a seed and forms a prosperous forest; generations will benefit from its virtue." },
      { ko: "오늘은 나의 소망을 방해하던 모든 장애물이 안개처럼 사라지는 경이로운 날이다.", en: "Today is a wonderful day when all obstacles that hindered your wish disappear like fog." },
      { ko: "나의 진심 어린 바람이 사람들의 마음을 움직여, 거대한 지지 세력을 형성한다.", en: "Your sincere wish moves people's hearts, forming a massive support group." },
      { ko: "꿈꾸는 자만이 가질 수 있는 특별한 아우라가 나의 성공을 더욱 빛나게 하리로다.", en: "The special aura that only dreamers can have will make your success shine even more." },
      { ko: "나의 소망이 현실이 되는 과정 자체가 타인에게는 커다란 영감이 되는구나.", en: "The process of your wish becoming reality itself is a great inspiration to others." },
      { ko: "오늘은 나의 간절한 소망이 담긴 문서가 승인되거나 계약되는 기쁨이 있다.", en: "There is joy today as a document containing your earnest wish is approved or contracted." },
      { ko: "나의 소망이 결실을 맺을 때, 그동안의 눈물은 진주보다 더 귀한 가치를 지닌다.", en: "When your wish bears fruit, the past tears hold more value than pearls." },
      { ko: "세상이 정해놓은 틀을 깨고 나만의 소망을 지킨 결과가 오늘 위대한 승리로 나타난다.", en: "The result of breaking the world's frame and keeping your own wish manifests as a great victory today." },
      { ko: "나의 열정이 소망의 엔진이 되어, 누구보다 빠르게 목표 지점에 도달하게 하도다.", en: "Your passion becomes the engine of your wish, reaching the goal point faster than anyone." },
      { ko: "오늘은 나의 소망을 실현해 줄 결정적인 정보나 도구를 얻게 되는 행운이 있다.", en: "There is luck today in obtaining decisive information or tools that will realize your wish." },
      { ko: "나의 소망이 이미 이루어졌음을 믿고 행동하라. 현실은 곧 나의 믿음을 따라온다.", en: "Act believing your wish is already fulfilled. Reality will soon follow your belief." },
      { ko: "고난은 소망을 더욱 단단하게 만드는 풀무질이니, 이제는 강철 같은 의지를 갖게 되었도다.", en: "Hardship is the bellows that makes the wish firmer; now you have a steel-like will." },
      { ko: "나의 순수한 바람이 세상에 선한 영향력을 끼치니, 부와 명예가 덤으로 따라온다.", en: "As your pure wish exerts a good influence on the world, wealth and honor follow as a bonus." },
      { ko: "오늘은 나의 소망을 위해 기도하던 이들과 함께 기쁨을 나누는 축제의 날이다.", en: "Today is a festival day to share joy with those who prayed for your wish." },
      { ko: "나의 소망이 뿌리를 깊게 내렸으니, 어떤 흔들림에도 무너지지 않는 성취가 되리라.", en: "Your wish has taken deep roots, so it will be an achievement that doesn't crumble under any shaking." },
      { ko: "포기라는 단어를 지우고 소망만을 남겼을 때, 비로소 진정한 기적이 시작되는구나.", en: "When you erase the word failure and leave only hope, true miracles finally begin." },
      { ko: "나의 소망이 하늘의 운때를 만났으니, 거침없이 몰아치는 성공의 파도를 타라.", en: "Your wish has met heaven's timing; ride the wave of success that surges without hesitation." },
      { ko: "오늘은 나의 오랜 꿈이 공식적으로 인정받아 세상에 널리 알려지는 영광의 날이다.", en: "Today is a day of glory when your long-standing dream is officially recognized and widely known." },
      { ko: "나의 소망이 결실을 맺으니, 인생의 사계절 중 가장 풍요로운 가을을 맞이하도다.", en: "As your wish bears fruit, you welcome the most prosperous autumn of your life's four seasons." },
      { ko: "오늘은 나의 무의식이 소망의 현실화를 돕기 위해 예리한 직감을 선물하는 날이다.", en: "Today is the day your subconscious gifts sharp intuition to help manifest your wish." },
      { ko: "나의 소망이 달성됨으로써 내가 속한 공동체 전체의 위상이 한 단계 격상되리라.", en: "By achieving your wish, the status of your entire community will be upgraded by one level." },
      { ko: "간절한 바람이 나를 잠 못 들게 하더니, 이제는 기쁨에 겨워 잠 못 이루는 날이 온다.", en: "Earnest desires kept you awake, and now comes the day you can't sleep for sheer joy." },
      { ko: "나의 소망을 지지하는 강력한 조력자가 나타나니, 천군만마를 얻은 듯 든든하도다.", en: "A powerful helper supporting your wish appears; it's as reassuring as gaining a thousand soldiers." },
      { ko: "오늘은 나의 소망이 씨앗에서 싹으로, 다시 커다란 나무로 성장하는 변곡점이다.", en: "Today is the inflection point where your wish grows from a seed to a sprout, and then into a large tree." },
      { ko: "나의 소망이 우연한 사건을 통해 필연적인 성공으로 연결되는 마법 같은 시기이다.", en: "It is a magical time when your wish is connected to inevitable success through an accidental event." },
      { ko: "소망이 현실이 된 지금, 더 큰 꿈을 꿀 자격이 내게 주어졌음을 기쁘게 받아들여라.", en: "Now that the wish has become reality, gladly accept that you are given the right to dream even bigger." },/* 데이터 삽입 예정 */ ]
  };

  const categories = Object.keys(fortunes);
  const pickRandom = (arr) => arr[Math.floor(Math.random() * arr.length)];

  let selectedCategoryName = "";
  let selectedFortune = null;

  // 1. 전체 랜덤 보기 (__ALL__) 인 경우
  if (requestedCategory === "__ALL__") {
    selectedCategoryName = pickRandom(categories);
    selectedFortune = pickRandom(fortunes[selectedCategoryName]);
  } 
  // 2. 특정 카테고리를 클릭한 경우
  else {
    // 선생님이 정하신 새로운 카테고리 명칭이 들어오는지 확인, 없으면 "행운운"을 기본값으로 사용
    selectedCategoryName = (requestedCategory && fortunes[requestedCategory]) ? requestedCategory : "행운운";
    selectedFortune = pickRandom(fortunes[selectedCategoryName]);
  }

  // 최종 리턴: 기존 UI 구조(theme, ref)를 완벽하게 유지합니다.
  return {
    ko: selectedFortune.ko,
    en: selectedFortune.en,
    ref: `Fortune • ${selectedCategoryName}`,
    theme: selectedCategoryName
  };
}