// src/utils/getRandomVerse.js
export function getRandomVerse() {
  const verses = [
        // 🕊 FAITH (믿음)
    { en: "I can do all things through Christ who strengthens me.", ko: "내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라.", ref: "Philippians 4:13", theme: "Faith" },
    { en: "Now faith is confidence in what we hope for and assurance about what we do not see.", ko: "믿음은 바라는 것들의 실상이요 보이지 않는 것들의 증거니라.", ref: "Hebrews 11:1", theme: "Faith" },
    { en: "We live by faith, not by sight.", ko: "우리는 믿음으로 행하고 보는 것으로 하지 아니함이라.", ref: "2 Corinthians 5:7", theme: "Faith" },
    { en: "Jesus said, ‘Everything is possible for one who believes.’", ko: "예수께서 이르시되 믿는 자에게는 능히 하지 못할 일이 없느니라.", ref: "Mark 9:23", theme: "Faith" },
    { en: "Faith comes from hearing the message, and the message is heard through the word about Christ.", ko: "믿음은 들음에서 나며 들음은 그리스도의 말씀으로 말미암느니라.", ref: "Romans 10:17", theme: "Faith" },
    { en: "If you have faith as small as a mustard seed, nothing will be impossible for you.", ko: "너희에게 겨자씨 한 알만한 믿음이 있으면 아무 것도 너희에게 불가능하지 아니하리라.", ref: "Matthew 17:20", theme: "Faith" },
    { en: "The righteous will live by faith.", ko: "오직 의인은 믿음으로 말미암아 살리라.", ref: "Romans 1:17", theme: "Faith" },
    { en: "Your faith has healed you; go in peace.", ko: "네 믿음이 너를 구원하였으니 평안히 가라.", ref: "Luke 8:48", theme: "Faith" },
    { en: "Without faith it is impossible to please God.", ko: "믿음이 없이는 하나님을 기쁘시게 하지 못하나니.", ref: "Hebrews 11:6", theme: "Faith" },
    { en: "Let us fix our eyes on Jesus, the pioneer and perfecter of faith.", ko: "믿음의 주요 또 온전하게 하시는 이인 예수를 바라보자.", ref: "Hebrews 12:2", theme: "Faith" },
    { en: "Stand firm in the faith; be courageous; be strong.", ko: "믿음에 굳게 서서 남자답게 강건하라.", ref: "1 Corinthians 16:13", theme: "Faith" },
    { en: "For everyone born of God overcomes the world.", ko: "무릇 하나님께로부터 난 자마다 세상을 이기느니라.", ref: "1 John 5:4", theme: "Faith" },
    { en: "The testing of your faith produces perseverance.", ko: "너희 믿음의 시련이 인내를 만들어 내는 줄 너희가 앎이라.", ref: "James 1:3", theme: "Faith" },
    { en: "Faith expresses itself through love.", ko: "사랑으로 역사하는 믿음뿐이니라.", ref: "Galatians 5:6", theme: "Faith" },
    { en: "Fight the good fight of the faith.", ko: "믿음의 선한 싸움을 싸우라.", ref: "1 Timothy 6:12", theme: "Faith" },
    { en: "Have faith in God.", ko: "하나님을 믿으라.", ref: "Mark 11:22", theme: "Faith" },
    { en: "Do not be afraid; just believe.", ko: "두려워하지 말고 믿기만 하라.", ref: "Mark 5:36", theme: "Faith" },
    { en: "Whatever you ask for in prayer, believe that you have received it, and it will be yours.", ko: "기도할 때 무엇이든지 믿고 구하는 것은 받은 줄로 믿으라.", ref: "Mark 11:24", theme: "Faith" },
    { en: "Trust in the Lord forever, for the Lord himself is the Rock eternal.", ko: "여호와를 영원히 신뢰하라 주 여호와는 영원한 반석이심이로다.", ref: "Isaiah 26:4", theme: "Faith" },
    { en: "Be on your guard; stand firm in the faith; be courageous; be strong.", ko: "믿음에 굳게 서서 남자답게 강건하라.", ref: "1 Corinthians 16:13", theme: "Faith" },

    // ❤ LOVE (사랑)
    { en: "Love your neighbor as yourself.", ko: "네 이웃을 네 자신과 같이 사랑하라.", ref: "Mark 12:31", theme: "Love" },
    { en: "God is love. Whoever lives in love lives in God, and God in them.", ko: "하나님은 사랑이시라 사랑 안에 거하는 자는 하나님 안에 거하고 하나님도 그의 안에 거하시느니라.", ref: "1 John 4:16", theme: "Love" },
    { en: "Let all that you do be done in love.", ko: "너희 모든 일을 사랑으로 행하라.", ref: "1 Corinthians 16:14", theme: "Love" },
    { en: "Love one another deeply, from the heart.", ko: "서로 뜨겁게 사랑하라.", ref: "1 Peter 1:22", theme: "Love" },
    { en: "Above all, love each other deeply, because love covers over a multitude of sins.", ko: "무엇보다도 서로 사랑할지니 사랑은 허다한 죄를 덮느니라.", ref: "1 Peter 4:8", theme: "Love" },
    { en: "We love because He first loved us.", ko: "우리가 사랑함은 그가 먼저 우리를 사랑하셨음이라.", ref: "1 John 4:19", theme: "Love" },
    { en: "Do everything in love.", ko: "모든 일을 사랑으로 행하라.", ref: "1 Corinthians 16:14", theme: "Love" },
    { en: "Love never fails.", ko: "사랑은 언제까지나 떨어지지 아니하느니라.", ref: "1 Corinthians 13:8", theme: "Love" },
    { en: "Greater love has no one than this: to lay down one’s life for one’s friends.", ko: "사람이 친구를 위하여 자기 목숨을 버리면 이보다 더 큰 사랑이 없나니.", ref: "John 15:13", theme: "Love" },
    { en: "Let us love one another, for love comes from God.", ko: "서로 사랑하자 사랑은 하나님께 속한 것이니.", ref: "1 John 4:7", theme: "Love" },
    { en: "Be completely humble and gentle; be patient, bearing with one another in love.", ko: "모든 겸손과 온유로 하고 오래 참음으로 사랑 가운데서 서로 용납하고.", ref: "Ephesians 4:2", theme: "Love" },
    { en: "My command is this: Love each other as I have loved you.", ko: "내가 너희를 사랑한 것 같이 너희도 서로 사랑하라.", ref: "John 15:12", theme: "Love" },
    { en: "Love does no harm to a neighbor. Therefore love is the fulfillment of the law.", ko: "사랑은 이웃에게 악을 행하지 아니하나니 그러므로 사랑은 율법의 완성이니라.", ref: "Romans 13:10", theme: "Love" },
    { en: "And now these three remain: faith, hope and love. But the greatest of these is love.", ko: "그런즉 믿음, 소망, 사랑 이 세 가지는 항상 있을 것인데 그 중의 제일은 사랑이라.", ref: "1 Corinthians 13:13", theme: "Love" },
    { en: "Hatred stirs up conflict, but love covers over all wrongs.", ko: "미움은 다툼을 일으켜도 사랑은 모든 허물을 가리우느니라.", ref: "Proverbs 10:12", theme: "Love" },
    { en: "Do to others as you would have them do to you.", ko: "남에게 대접을 받고자 하는 대로 너희도 남을 대접하라.", ref: "Luke 6:31", theme: "Love" },
    { en: "Let love and faithfulness never leave you.", ko: "인자와 진리가 네게서 떠나지 말게 하라.", ref: "Proverbs 3:3", theme: "Love" },
    { en: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.", ko: "서로 친절하게 하며 불쌍히 여기며 서로 용서하기를 하나님이 너희를 용서하심 같이 하라.", ref: "Ephesians 4:32", theme: "Love" },
    { en: "Love your enemies and pray for those who persecute you.", ko: "너희 원수를 사랑하며 너희를 박해하는 자를 위하여 기도하라.", ref: "Matthew 5:44", theme: "Love" },
    { en: "Let brotherly love continue.", ko: "형제 사랑하기를 계속하라.", ref: "Hebrews 13:1", theme: "Love" },

    // 🌟 HOPE (소망)
    { en: "May the God of hope fill you with all joy and peace as you trust in Him.", ko: "소망의 하나님이 모든 기쁨과 평강을 믿음 안에서 너희에게 충만하게 하사.", ref: "Romans 15:13", theme: "Hope" },
    { en: "For I know the plans I have for you, declares the Lord, plans to give you hope and a future.", ko: "너희를 향한 나의 생각은 재앙이 아니라 평안이요 미래와 소망을 주려 하는 생각이라.", ref: "Jeremiah 29:11", theme: "Hope" },
    { en: "Those who hope in the Lord will renew their strength.", ko: "오직 여호와를 앙망하는 자는 새 힘을 얻으리니.", ref: "Isaiah 40:31", theme: "Hope" },
    { en: "We have this hope as an anchor for the soul, firm and secure.", ko: "이 소망은 우리 영혼의 닻 같아서 튼튼하고 견고하며.", ref: "Hebrews 6:19", theme: "Hope" },
    { en: "The Lord is good to those whose hope is in Him.", ko: "여호와께서는 그를 바라는 영혼에게 선을 베푸시나니.", ref: "Lamentations 3:25", theme: "Hope" },
    { en: "Be joyful in hope, patient in affliction, faithful in prayer.", ko: "소망 중에 즐거워하며 환난 중에 참으며 기도에 항상 힘쓰라.", ref: "Romans 12:12", theme: "Hope" },
    { en: "Rejoice in hope of the glory of God.", ko: "하나님의 영광을 바라고 즐거워하느니라.", ref: "Romans 5:2", theme: "Hope" },
    { en: "My hope is in You all day long.", ko: "주여 나는 종일 주를 바라나이다.", ref: "Psalm 25:5", theme: "Hope" },
    { en: "The Lord delights in those who put their hope in His unfailing love.", ko: "여호와는 인자하심을 바라는 자들을 기뻐하시느니라.", ref: "Psalm 147:11", theme: "Hope" },
    { en: "Hope deferred makes the heart sick, but a longing fulfilled is a tree of life.", ko: "소망이 더디 이루어지면 마음이 상하나 소원이 이루어지면 곧 생명나무라.", ref: "Proverbs 13:12", theme: "Hope" },
    { en: "Be strong and take heart, all you who hope in the Lord.", ko: "여호와를 바라는 너희들아 강하고 담대하라.", ref: "Psalm 31:24", theme: "Hope" },
    { en: "In His word I put my hope.", ko: "주의 말씀에 내가 소망을 두었나이다.", ref: "Psalm 130:5", theme: "Hope" },
    { en: "Christ in you, the hope of glory.", ko: "너희 안에 계신 그리스도는 영광의 소망이니라.", ref: "Colossians 1:27", theme: "Hope" },
    { en: "We wait for the blessed hope—the appearing of the glory of our great God and Savior, Jesus Christ.", ko: "복스러운 소망과 우리의 구주 예수 그리스도의 영광이 나타나심을 기다리게 하셨으니.", ref: "Titus 2:13", theme: "Hope" },
    { en: "Put your hope in God, for I will yet praise Him.", ko: "너는 하나님을 바라라 그가 나의 구원이시오 나의 하나님이시로다.", ref: "Psalm 42:11", theme: "Hope" },
    { en: "You are my refuge and my portion in the land of the living.", ko: "주는 나의 피난처시요 생존자들의 가운데서 나의 분깃이시니이다.", ref: "Psalm 142:5", theme: "Hope" },
    { en: "The eyes of the Lord are on those who hope in His unfailing love.", ko: "여호와의 눈은 그를 경외하는 자 곧 그의 인자하심을 바라는 자를 살피시는도다.", ref: "Psalm 33:18", theme: "Hope" },
    { en: "Let us hold unswervingly to the hope we profess, for He who promised is faithful.", ko: "약속하신 이는 미쁘시니 우리가 믿는 도리를 굳게 잡을지어다.", ref: "Hebrews 10:23", theme: "Hope" },
    { en: "Rejoice in hope, be patient in tribulation, be constant in prayer.", ko: "소망 중에 즐거워하며 환난 중에 참으며 기도에 항상 힘쓰라.", ref: "Romans 12:12", theme: "Hope" },
    { en: "Blessed is the one who trusts in the Lord, whose confidence is in Him.", ko: "무릇 여호와를 의지하며 여호와를 의뢰하는 그 사람은 복이 있도다.", ref: "Jeremiah 17:7", theme: "Hope" },

    // 🌿 COMFORT (위로)
    { en: "Come to me, all you who are weary and burdened, and I will give you rest.", ko: "수고하고 무거운 짐 진 자들아 다 내게로 오라 내가 너희를 쉬게 하리라.", ref: "Matthew 11:28", theme: "Comfort" },
    { en: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", ko: "여호와는 마음이 상한 자에게 가까이 하시고 중심에 통회하는 자를 구원하시는도다.", ref: "Psalm 34:18", theme: "Comfort" },
    { en: "He heals the brokenhearted and binds up their wounds.", ko: "그는 마음이 상한 자를 고치시며 그들의 상처를 싸매시는도다.", ref: "Psalm 147:3", theme: "Comfort" },
    { en: "Even though I walk through the valley of the shadow of death, I will fear no evil, for You are with me.", ko: "내가 사망의 음침한 골짜기를 다닐지라도 해를 두려워하지 않을 것은 주께서 나와 함께 하심이라.", ref: "Psalm 23:4", theme: "Comfort" },
    { en: "Blessed are those who mourn, for they will be comforted.", ko: "애통하는 자는 복이 있나니 그들이 위로를 받을 것임이요.", ref: "Matthew 5:4", theme: "Comfort" },
    { en: "Cast all your anxiety on Him because He cares for you.", ko: "너희 염려를 다 주께 맡기라 이는 그가 너희를 돌보심이라.", ref: "1 Peter 5:7", theme: "Comfort" },
    { en: "The Lord is my light and my salvation—whom shall I fear?", ko: "여호와는 나의 빛이요 나의 구원이시니 내가 누구를 두려워하리요.", ref: "Psalm 27:1", theme: "Comfort" },
    { en: "God is our refuge and strength, an ever-present help in trouble.", ko: "하나님은 우리의 피난처시요 힘이시니 환난 중에 만날 큰 도움이시라.", ref: "Psalm 46:1", theme: "Comfort" },
    { en: "When I am afraid, I put my trust in You.", ko: "내가 두려워하는 날에는 내가 주를 의지하리이다.", ref: "Psalm 56:3", theme: "Comfort" },
    { en: "Peace I leave with you; my peace I give you.", ko: "평안을 너희에게 끼치노니 곧 나의 평안을 너희에게 주노라.", ref: "John 14:27", theme: "Comfort" },
    { en: "The Lord gives strength to His people; the Lord blesses His people with peace.", ko: "여호와께서 자기 백성에게 힘을 주시며 평강의 복을 주시리로다.", ref: "Psalm 29:11", theme: "Comfort" },
    { en: "You are my hiding place; You will protect me from trouble and surround me with songs of deliverance.", ko: "주는 나의 은신처시오 환난에서 나를 보호하시며 구원의 노래로 나를 둘러싸시리이다.", ref: "Psalm 32:7", theme: "Comfort" },
    { en: "My grace is sufficient for you, for my power is made perfect in weakness.", ko: "내 은혜가 네게 족하도다 이는 내 능력이 약한 데서 온전하여짐이라.", ref: "2 Corinthians 12:9", theme: "Comfort" },
    { en: "The eternal God is your refuge, and underneath are the everlasting arms.", ko: "영원하신 하나님이 네 처소가 되시며 영원한 팔이 네 아래에 있도다.", ref: "Deuteronomy 33:27", theme: "Comfort" },
    { en: "The Lord will fight for you; you need only to be still.", ko: "여호와께서 너희를 위하여 싸우시리니 너희는 가만히 있을지니라.", ref: "Exodus 14:14", theme: "Comfort" },
    { en: "He will wipe every tear from their eyes.", ko: "하나님께서 그들의 눈에서 모든 눈물을 씻기시리니.", ref: "Revelation 21:4", theme: "Comfort" },
    { en: "The righteous cry out, and the Lord hears them; He delivers them from all their troubles.", ko: "의인이 부르짖으매 여호와께서 들으시고 그들의 모든 환난에서 건지셨도다.", ref: "Psalm 34:17", theme: "Comfort" },
    { en: "The Lord is my helper; I will not be afraid.", ko: "주께서 나를 돕으시니 내가 두려워하지 아니하겠노라.", ref: "Hebrews 13:6", theme: "Comfort" },
    { en: "When you pass through the waters, I will be with you.", ko: "네가 물 가운데로 지날 때에 내가 너와 함께 할 것이라.", ref: "Isaiah 43:2", theme: "Comfort" },
    { en: "Your rod and Your staff, they comfort me.", ko: "주의 지팡이와 막대기가 나를 안위하시나이다.", ref: "Psalm 23:4", theme: "Comfort" },

// 🕊 GRATITUDE (감사)
{ en: "Give thanks to the Lord, for He is good; His love endures forever.", ko: "여호와께 감사하라 그는 선하시며 그 인자하심이 영원함이로다.", ref: "Psalm 107:1", theme: "Gratitude" },
{ en: "Give thanks in all circumstances; for this is God’s will for you in Christ Jesus.", ko: "범사에 감사하라 이것이 그리스도 예수 안에서 너희를 향하신 하나님의 뜻이니라.", ref: "1 Thessalonians 5:18", theme: "Gratitude" },
{ en: "Enter His gates with thanksgiving and His courts with praise.", ko: "감사함으로 그의 문에 들어가며 찬송함으로 그의 궁정에 들어가서 그에게 감사하며 그의 이름을 송축할지어다.", ref: "Psalm 100:4", theme: "Gratitude" },
{ en: "Let them give thanks to the Lord for His unfailing love.", ko: "여호와의 인자하심과 인생에게 행하신 기이한 일로 말미암아 그를 찬송할지로다.", ref: "Psalm 107:8", theme: "Gratitude" },
{ en: "I will give thanks to You, Lord, with all my heart.", ko: "내가 전심으로 여호와께 감사하며 주의 모든 기이한 일을 전하리이다.", ref: "Psalm 9:1", theme: "Gratitude" },
{ en: "Let the peace of Christ rule in your hearts and be thankful.", ko: "그리스도의 평강이 너희 마음을 주장하게 하라 너희는 감사하는 자가 되라.", ref: "Colossians 3:15", theme: "Gratitude" },
{ en: "Offer to God a sacrifice of thanksgiving.", ko: "감사로 하나님께 제사를 드리며.", ref: "Psalm 50:14", theme: "Gratitude" },
{ en: "Give thanks to the Lord, call on His name; make known among the nations what He has done.", ko: "여호와께 감사하며 그의 이름을 불러 그가 행하신 일을 만민 중에 알게 할지어다.", ref: "Psalm 105:1", theme: "Gratitude" },
{ en: "Do not be anxious about anything, but in everything by prayer and thanksgiving present your requests to God.", ko: "아무것도 염려하지 말고 다만 모든 일에 기도와 간구로 너희 구할 것을 감사함으로 하나님께 아뢰라.", ref: "Philippians 4:6", theme: "Gratitude" },
{ en: "Thanks be to God for His indescribable gift!", ko: "말로 다 할 수 없는 그의 은사로 말미암아 하나님께 감사하노라.", ref: "2 Corinthians 9:15", theme: "Gratitude" },
{ en: "Let us come before Him with thanksgiving.", ko: "감사함으로 그 앞에 나아가며.", ref: "Psalm 95:2", theme: "Gratitude" },
{ en: "Sing to the Lord with grateful praise.", ko: "감사함으로 여호와께 노래하며 수금으로 하나님께 찬양할지어다.", ref: "Psalm 147:7", theme: "Gratitude" },
{ en: "I will praise God’s name in song and glorify Him with thanksgiving.", ko: "내가 노래로 하나님의 이름을 찬송하며 감사함으로 하나님을 위대하게 하리니.", ref: "Psalm 69:30", theme: "Gratitude" },
{ en: "Give thanks to the Lord, for He is good.", ko: "여호와께 감사하라 그는 선하시며.", ref: "Psalm 136:1", theme: "Gratitude" },
{ en: "Devote yourselves to prayer, being watchful and thankful.", ko: "기도를 계속하고 감사함으로 깨어 있으라.", ref: "Colossians 4:2", theme: "Gratitude" },
{ en: "Let us continually offer to God a sacrifice of praise.", ko: "하나님께 항상 찬미의 제사를 드리자.", ref: "Hebrews 13:15", theme: "Gratitude" },
{ en: "Praise the Lord, my soul, and forget not all His benefits.", ko: "내 영혼아 여호와를 송축하며 그의 모든 은택을 잊지 말지어다.", ref: "Psalm 103:2", theme: "Gratitude" },
{ en: "I will give You thanks forever for what You have done.", ko: "주는 주의 이름이 선하시므로 내가 영원히 주께 감사하리이다.", ref: "Psalm 52:9", theme: "Gratitude" },
{ en: "Let the word of Christ dwell in you richly as you sing with gratitude in your hearts to God.", ko: "감사하는 마음으로 하나님께 찬송하라.", ref: "Colossians 3:16", theme: "Gratitude" },
{ en: "The Lord has done great things for us, and we are filled with joy.", ko: "여호와께서 우리를 위하여 큰 일을 행하셨으니 우리는 기쁘도다.", ref: "Psalm 126:3", theme: "Gratitude" },

// ☮ PEACE (평안)
{ en: "Peace I leave with you; my peace I give you.", ko: "평안을 너희에게 끼치노니 곧 나의 평안을 너희에게 주노라.", ref: "John 14:27", theme: "Peace" },
{ en: "Do not be anxious about anything, but in every situation, present your requests to God.", ko: "아무 것도 염려하지 말고 오직 모든 일에 기도와 간구로 하나님께 아뢰라.", ref: "Philippians 4:6", theme: "Peace" },
{ en: "The peace of God, which transcends all understanding, will guard your hearts and your minds.", ko: "모든 지각에 뛰어난 하나님의 평강이 너희 마음과 생각을 지키시리라.", ref: "Philippians 4:7", theme: "Peace" },
{ en: "The Lord bless you and keep you; the Lord give you peace.", ko: "여호와는 네게 복을 주시고 평강 주시기를 원하노라.", ref: "Numbers 6:26", theme: "Peace" },
{ en: "You will keep in perfect peace those whose minds are steadfast.", ko: "주께서 심지가 견고한 자를 평강 가운데 지키시리니.", ref: "Isaiah 26:3", theme: "Peace" },
{ en: "Let the peace of Christ rule in your hearts.", ko: "그리스도의 평강이 너희 마음을 주장하게 하라.", ref: "Colossians 3:15", theme: "Peace" },
{ en: "Blessed are the peacemakers, for they will be called children of God.", ko: "화평하게 하는 자는 복이 있나니 그들이 하나님의 아들이라 일컬음을 받을 것임이요.", ref: "Matthew 5:9", theme: "Peace" },
{ en: "Turn from evil and do good; seek peace and pursue it.", ko: "악을 버리고 선을 행하며 화평을 찾아 따르라.", ref: "Psalm 34:14", theme: "Peace" },
{ en: "Great peace have those who love Your law.", ko: "주의 법을 사랑하는 자에게는 큰 평안이 있으니.", ref: "Psalm 119:165", theme: "Peace" },
{ en: "Make every effort to live in peace with everyone.", ko: "모든 사람과 더불어 화평함과 거룩함을 따르라.", ref: "Hebrews 12:14", theme: "Peace" },
{ en: "The Lord gives strength to His people; the Lord blesses His people with peace.", ko: "여호와께서 자기 백성에게 힘을 주시며 평강의 복을 주시리로다.", ref: "Psalm 29:11", theme: "Peace" },
{ en: "In peace I will lie down and sleep, for You alone, Lord, make me dwell in safety.", ko: "내가 평안히 눕고 자기도 하리니 오직 주께서 나를 안전히 살게 하시나이다.", ref: "Psalm 4:8", theme: "Peace" },
{ en: "The fruit of the Spirit is love, joy, peace...", ko: "성령의 열매는 사랑과 희락과 화평과...", ref: "Galatians 5:22", theme: "Peace" },
{ en: "Seek peace and pursue it.", ko: "화평을 찾아 따르라.", ref: "1 Peter 3:11", theme: "Peace" },
{ en: "The God of peace will soon crush Satan under your feet.", ko: "평강의 하나님께서 속히 사탄을 너희 발 아래 상하게 하시리라.", ref: "Romans 16:20", theme: "Peace" },
{ en: "The mind governed by the Spirit is life and peace.", ko: "영의 생각은 생명과 평안이니라.", ref: "Romans 8:6", theme: "Peace" },
{ en: "Mercy, peace and love be yours in abundance.", ko: "긍휼과 평강과 사랑이 너희에게 더욱 많을지어다.", ref: "Jude 1:2", theme: "Peace" },
{ en: "Depart from evil and do good; seek peace and pursue it.", ko: "악을 버리고 선을 행하며 화평을 찾아 따르라.", ref: "Psalm 34:14", theme: "Peace" },
{ en: "The Lord will give strength to His people; the Lord will bless His people with peace.", ko: "여호와께서 자기 백성에게 힘을 주시며 평강의 복을 주시리로다.", ref: "Psalm 29:11", theme: "Peace" },
{ en: "Live in peace, and the God of love and peace will be with you.", ko: "평안히 지내라 그러면 사랑과 평강의 하나님이 너희와 함께 계시리라.", ref: "2 Corinthians 13:11", theme: "Peace" },

// 💡 WISDOM (지혜)
{ en: "The fear of the Lord is the beginning of wisdom.", ko: "여호와를 경외하는 것이 지혜의 근본이요.", ref: "Proverbs 9:10", theme: "Wisdom" },
{ en: "If any of you lacks wisdom, let him ask of God.", ko: "너희 중에 누구든지 지혜가 부족하거든 하나님께 구하라.", ref: "James 1:5", theme: "Wisdom" },
{ en: "Blessed are those who find wisdom.", ko: "지혜를 얻은 자는 복이 있나니.", ref: "Proverbs 3:13", theme: "Wisdom" },
{ en: "Wisdom is more precious than rubies.", ko: "지혜는 진주보다 귀하니.", ref: "Proverbs 3:15", theme: "Wisdom" },
{ en: "Trust in the Lord with all your heart and lean not on your own understanding.", ko: "너는 마음을 다하여 여호와를 신뢰하고 네 명철을 의지하지 말라.", ref: "Proverbs 3:5", theme: "Wisdom" },
{ en: "When pride comes, then comes disgrace, but with humility comes wisdom.", ko: "교만이 오면 욕도 오거니와 겸손한 자에게는 지혜가 있느니라.", ref: "Proverbs 11:2", theme: "Wisdom" },
{ en: "For the Lord gives wisdom; from His mouth come knowledge and understanding.", ko: "여호와는 지혜를 주시며 그의 입에서는 지식과 명철이 나오며.", ref: "Proverbs 2:6", theme: "Wisdom" },
{ en: "Listen to advice and accept discipline, and at the end you will be counted among the wise.", ko: "훈계를 듣고 명철한 자의 말을 받아들이라.", ref: "Proverbs 19:20", theme: "Wisdom" },
{ en: "A gentle answer turns away wrath, but a harsh word stirs up anger.", ko: "유순한 대답은 분노를 쉬게 하여도 과격한 말은 노를 일으키느니라.", ref: "Proverbs 15:1", theme: "Wisdom" },
{ en: "Do not be wise in your own eyes; fear the Lord and shun evil.", ko: "스스로 지혜롭게 여기지 말지어다.", ref: "Proverbs 3:7", theme: "Wisdom" },

// 🤍 FORGIVENESS (용서)
{ en: "Forgive, and you will be forgiven.", ko: "용서하라 그리하면 너희도 용서함을 받을 것이요.", ref: "Luke 6:37", theme: "Forgiveness" },
{ en: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.", ko: "서로 친절하게 하며 불쌍히 여기며 서로 용서하기를 하나님이 너희를 용서하심 같이 하라.", ref: "Ephesians 4:32", theme: "Forgiveness" },
{ en: "If you forgive others when they sin against you, your heavenly Father will also forgive you.", ko: "너희가 사람의 잘못을 용서하면 너희 하늘 아버지께서도 너희를 용서하시리라.", ref: "Matthew 6:14", theme: "Forgiveness" },
{ en: "Bear with each other and forgive one another if any of you has a grievance.", ko: "서로 용납하며 누가 누구에게 불만이 있거든 서로 용서하되.", ref: "Colossians 3:13", theme: "Forgiveness" },
{ en: "Love keeps no record of wrongs.", ko: "사랑은 악한 것을 생각하지 아니하며.", ref: "1 Corinthians 13:5", theme: "Forgiveness" },
{ en: "Blessed are the merciful, for they will be shown mercy.", ko: "긍휼히 여기는 자는 복이 있나니 그들이 긍휼히 여김을 받을 것임이요.", ref: "Matthew 5:7", theme: "Forgiveness" },
{ en: "As the Lord has forgiven you, so you also must forgive.", ko: "주께서 너희를 용서하신 것 같이 너희도 그리하라.", ref: "Colossians 3:13", theme: "Forgiveness" },
{ en: "Do not judge, and you will not be judged; forgive, and you will be forgiven.", ko: "비판하지 말라 그리하면 너희가 비판을 받지 아니할 것이요.", ref: "Luke 6:37", theme: "Forgiveness" },
{ en: "Father, forgive them, for they do not know what they are doing.", ko: "아버지여 저희를 사하여 주옵소서 자기들이 하는 것을 알지 못함이니이다.", ref: "Luke 23:34", theme: "Forgiveness" },
{ en: "The blood of Jesus purifies us from all sin.", ko: "예수의 피가 우리를 모든 죄에서 깨끗하게 하실 것이요.", ref: "1 John 1:7", theme: "Forgiveness" },
  ];

  return verses[Math.floor(Math.random() * verses.length)];
}
   

